<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<meta name="shinylive:serviceworker_dir" content=".">
<script src="site_libs/quarto-contrib/shinylive-0.10.8/shinylive/load-shinylive-sw.js" type="module"></script>
<script src="site_libs/quarto-contrib/shinylive-0.10.8/shinylive/run-python-blocks.js" type="module"></script>
<link href="site_libs/quarto-contrib/shinylive-0.10.8/shinylive/shinylive.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/shinylive-quarto-css/shinylive-quarto.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.36">

  <title>Hypothesis Testing – Hypothesis Testing and p-Values</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-d61c63afcaa0ef5b8dee87d0d06ec23f.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

  <link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Hypothesis Testing and <span class="math inline">\(p\)</span>-Values</h1>

<div class="quarto-title-authors">
</div>

</section>
<section id="navigation-of-this-module" class="title-slide slide level1 h2 center">
<h1>Navigation of this module</h1>
<ul>
<li>Questions
<ul>
<li>Answers to some questions will be sequentially revealed</li>
<li>Think about the answer; Example:</li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li>What is 2 + 2?</li>
</ul>
</div>
<div class="fragment">
<p><span class="math display">\[2 + 2 = 4\]</span></p>
</div>
</section>

<section id="navigation-of-this-module-1" class="title-slide slide level1 h2 center">
<h1>Navigation of this module</h1>
<div class="fragment">
<ul>
<li>Scrolling
<ul>
<li>To advance most slides, scroll to the right</li>
<li>For more depth for some topics or learning checks, you can scroll down</li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Plots
<ul>
<li>If any plots look like a strange size or cut-off along the edges, <span style="color: blue;">try refreshing the page in your web browser</span>.</li>
</ul></li>
</ul>
</div>
</section>

<section id="main-learning-goals" class="title-slide slide level1 h2 center">
<h1>Main learning goals</h1>
<p>By completing this module, it is hoped that students can:</p>
<ul>
<li>Interpret a <span class="math inline">\(p\)</span>-value in the context of null hypothesis significance testing</li>
<li>Understand the difference between <span class="math inline">\(p\)</span>-values and <span class="math inline">\(\alpha\)</span></li>
<li>Understand the correspondence between a <span class="math inline">\(p\)</span>-value and an obtained test statistic</li>
</ul>
<p>This module does not yet provide complete coverage of:</p>
<ul>
<li>Alternatives to <span class="math inline">\(p\)</span>-values or null hypothesis significance testing</li>
</ul>
</section>

<section id="pre-requisite-knowledge" class="title-slide slide level1 h2 center">
<h1>Pre-Requisite Knowledge</h1>
<p>This module assumes some prior knowledge of:</p>
<ul>
<li>Sampling distributions and the central limit theorem</li>
<li>Normal distributions</li>
<li>Standardized scores or Z-scores</li>
<li>Basics of hypothesis testing</li>
</ul>
<p>A refresher of some of these concepts is attempted <!--(probability, standardized scores or z-scores).--></p>
</section>

<section id="research-question" class="title-slide slide level1 h2 center" data-auto-animate="true">
<h1 data-id="quarto-animate-title">Research Question</h1>
<p>Researchers studying quality of life are often interested in <span style="color: blue;">well-being</span>, an overall rating of one’s emotional, physical, and social health.</p>
<ul>
<li>We obtain a simple random sample of <span class="math inline">\(n=30\)</span> well-being scores from university students.</li>
<li>Scores range from 0 to 100. Higher scores indicate better well-being.</li>
<li>Assume a known population variance: <span class="math inline">\(\sigma^2 = 25\)</span></li>
</ul>
<p><span style="color: blue;">Research question</span>: Does the population of university students have a mean well-being score different than 50?</p>
</section>

<section id="research-question-1" class="title-slide slide level1 h2 center" data-auto-animate="true">
<h1 data-id="quarto-animate-title">Research Question</h1>
<p><span style="color: blue;">Research question</span>: Does the population of university students have a mean well-being score different than 50?</p>
<div class="fragment">
<ul>
<li>How can we write the null and alternative hypothesis?</li>
</ul>
</div>
<div class="fragment">
<p><span class="math display">\[H_0: \mu = 50\]</span> <span class="math display">\[H_a: \mu \ne 50\]</span></p>
</div>
</section>

<section id="research-question-2" class="title-slide slide level1 h2 center">
<h1>Research Question</h1>
<p><span style="color: blue;">Research question</span>: Does the population of university students have a mean well-being score equal to 50?</p>
<p>Suppose with <span class="math inline">\(n=30\)</span>, we obtain <span class="math inline">\(\bar{x} = 52\)</span></p>
<div class="fragment">
<ul>
<li>Is <span class="math inline">\(\bar{x} = 52\)</span> equal to the population mean?</li>
</ul>
</div>
<div class="fragment">
<p>No, but it is an <em>estimate</em> of the population mean for university students</p>
</div>
</section>

<section id="research-question-3" class="title-slide slide level1 h2 center" data-auto-animate="true">
<h1 data-id="quarto-animate-title">Research Question</h1>
<div class="fragment" data-fragment-index="1">
<ul>
<li>How can we use inferential statistics to help answer the research question?</li>
</ul>
</div>
<div class="r-stack">
<div class="fragment fade-in-then-out" data-fragment-index="2">
<ul>
<li>We can compare <span class="math inline">\(\bar{x} = 52\)</span> to the sampling distribution of the mean under <span class="math inline">\(H_0\)</span></li>
<li>This distribution assumes:
<ul>
<li><span class="math inline">\(n=30\)</span> (our sample size)</li>
<li><span class="math inline">\(\mu = 50\)</span> (the mean under <span class="math inline">\(H_0\)</span>)</li>
<li><span class="math inline">\(\sigma^2 = 25\)</span> (the assumed population variance)</li>
</ul></li>
</ul>
</div>
<div class="fragment fade-in" data-fragment-index="3">
<ul>
<li>To understand this distribution may require:
<ul>
<li>Knowledge of sampling distributions and the central limit theorem</li>
<li>(Standard) Normal distributions</li>
<li>Standard scores (or Z-scores)</li>
</ul></li>
</ul>
</div>
</div>
</section>

<section>
<section id="review-sampling-distributions" class="title-slide slide level1 center">
<h1>Review: Sampling distributions</h1>
<p>Scroll down for a review of sampling distributions, or advance to the right to skip</p>
</section>
<section id="imagine-mu-50-and-sigma2-25" class="slide level2 smaller">
<h2>Imagine <span class="math inline">\(\mu = 50\)</span> and <span class="math inline">\(\sigma^2 = 25\)</span></h2>
<div class="r-stack">
<div class="fragment fade-out" data-fragment-index="1">
<p>If true, pretend we can do the following:</p>
<ol type="1">
<li>Obtain a sample of <span class="math inline">\(n=30\)</span> and record the mean well-being score.</li>
<li>Repeat Step 1 many (e.g., ten-thousand) times.</li>
<li>Plot the distribution of the sample means:</li>
</ol>
</div>
<div class="fragment fade-in" data-fragment-index="1">
<ul>
<li>What special name does this distribution have?</li>
</ul>
<p><span class="fragment" data-fragment-index="2">Sampling distribution of the mean</span></p>
<ul>
<li>Was this distribution created assuming <span class="math inline">\(H_0\)</span> is true?</li>
</ul>
<p><span class="fragment" data-fragment-index="3">Yes, under this thought experiment, we assumed <span class="math inline">\(\mu = 50\)</span>; its standard deviation (i.e., standard error) is <span class="math inline">\(\sqrt{25/30} \approx .913\)</span></span></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-2-1.png" style="height:50.0%" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sampling-distribution" class="slide level2 smaller">
<h2>Sampling distribution</h2>
<ul>
<li>Suppose we want to know how many sample means are above 52. How can we know?</li>
</ul>
<p><span class="fragment" data-fragment-index="1">Count the number of sample means with a well-being score above 52. In this case, there are 129 out of 10,000 sample means above 52. We can represent this number as a percentage (1.29%) or proportion (.0129).</span></p>
<div class="r-stack">
<div class="fragment fade-out" data-fragment-index="1">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-3-1.png" style="height:50.0%" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment fade-in" data-fragment-index="1">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-4-1.png" style="height:50.0%" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sampling-distribution-cut-offs" class="slide level2">
<h2>Sampling distribution cut-offs</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb1-1"><a></a>#| '!! shinylive warning !!': |</span>
<span id="cb1-2"><a></a>#|   shinylive does not work in self-contained HTML documents.</span>
<span id="cb1-3"><a></a>#|   Please set `embed-resources: false` in your metadata.</span>
<span id="cb1-4"><a></a>#| standalone: true</span>
<span id="cb1-5"><a></a>#| panel: fill</span>
<span id="cb1-6"><a></a>#| fig-align: center</span>
<span id="cb1-7"><a></a>#| viewerHeight: 600</span>
<span id="cb1-8"><a></a>library(tibble)</span>
<span id="cb1-9"><a></a>library(munsell)</span>
<span id="cb1-10"><a></a>library(shiny)</span>
<span id="cb1-11"><a></a>library(ggplot2)</span>
<span id="cb1-12"><a></a></span>
<span id="cb1-13"><a></a>ui &lt;- fluidPage(</span>
<span id="cb1-14"><a></a>  plotOutput(outputId = "sampDistPlot"),</span>
<span id="cb1-15"><a></a>  sliderInput("cutoff", "Cut-off:", min = 48, max = 52, value = 51, step = 1)</span>
<span id="cb1-16"><a></a>)</span>
<span id="cb1-17"><a></a></span>
<span id="cb1-18"><a></a>server &lt;- function(input, output) {</span>
<span id="cb1-19"><a></a>  theme_minimalism &lt;- function(base_size = 20) {</span>
<span id="cb1-20"><a></a>    theme_minimal(base_size = base_size) + # ggplot's minimal theme hides many unnecessary features of plot</span>
<span id="cb1-21"><a></a>      theme(</span>
<span id="cb1-22"><a></a>        # make modifications to the theme</span>
<span id="cb1-23"><a></a>        panel.grid.major.y = element_blank(), # hide major grid for y axis</span>
<span id="cb1-24"><a></a>        panel.grid.minor.y = element_blank(), # hide minor grid for y axis</span>
<span id="cb1-25"><a></a>        panel.grid.major.x = element_blank(), # hide major grid for x axis</span>
<span id="cb1-26"><a></a>        panel.grid.minor.x = element_blank(), # hide minor grid for x axis</span>
<span id="cb1-27"><a></a>        #text=element_text(size=14),           # font aesthetics</span>
<span id="cb1-28"><a></a>        #axis.text=element_text(size=12),</span>
<span id="cb1-29"><a></a>        #axis.title=element_text(size=14,face="bold"))</span>
<span id="cb1-30"><a></a>        axis.title = element_text(face = "bold")</span>
<span id="cb1-31"><a></a>      )</span>
<span id="cb1-32"><a></a>  }</span>
<span id="cb1-33"><a></a></span>
<span id="cb1-34"><a></a>  output$sampDistPlot &lt;- renderPlot({</span>
<span id="cb1-35"><a></a>    lower &lt;- 47</span>
<span id="cb1-36"><a></a>    upper &lt;- 53</span>
<span id="cb1-37"><a></a>    mu &lt;- 50</span>
<span id="cb1-38"><a></a>    #stdev &lt;- 5</span>
<span id="cb1-39"><a></a></span>
<span id="cb1-40"><a></a>    set.seed(1234) #So we get the same results as above</span>
<span id="cb1-41"><a></a>    dat &lt;- round(rnorm(10000, 50, sqrt(25 / 30)), 1)</span>
<span id="cb1-42"><a></a></span>
<span id="cb1-43"><a></a>    sampdist &lt;- data.frame(x = dat) #Converts the above to a dataframe</span>
<span id="cb1-44"><a></a>    #sampdist &lt;- sampdist %&gt;% dplyr::mutate(aboveCutoff = ifelse(x &gt; input$cutoff, T,F)) #Adds a column counting if a given value is Above or Below the Sample Mean</span>
<span id="cb1-45"><a></a>    sampdist &lt;- sampdist %&gt;%</span>
<span id="cb1-46"><a></a>      dplyr::mutate(</span>
<span id="cb1-47"><a></a>        aboveCutoff = ifelse(x &gt; input$cutoff, "Above Cut-off", "Below Cut-off")</span>
<span id="cb1-48"><a></a>      ) #Adds a column counting if a given value is Above or Below the Sample Mean</span>
<span id="cb1-49"><a></a>    percent &lt;- (length(which(sampdist$aboveCutoff == "Above Cut-off")) /</span>
<span id="cb1-50"><a></a>      10000) *</span>
<span id="cb1-51"><a></a>      100</span>
<span id="cb1-52"><a></a></span>
<span id="cb1-53"><a></a>    ggplot(data = sampdist, aes(x, color = aboveCutoff, fill = aboveCutoff)) +</span>
<span id="cb1-54"><a></a>      geom_histogram(binwidth = .1) +</span>
<span id="cb1-55"><a></a>      annotate(</span>
<span id="cb1-56"><a></a>        "text",</span>
<span id="cb1-57"><a></a>        x = 51,</span>
<span id="cb1-58"><a></a>        y = 1200,</span>
<span id="cb1-59"><a></a>        label = paste0(</span>
<span id="cb1-60"><a></a>          percent,</span>
<span id="cb1-61"><a></a>          "% of the distribution \n has a sample mean above ",</span>
<span id="cb1-62"><a></a>          input$cutoff</span>
<span id="cb1-63"><a></a>        ),</span>
<span id="cb1-64"><a></a>        vjust = 1,</span>
<span id="cb1-65"><a></a>        hjust = 1</span>
<span id="cb1-66"><a></a>      ) +</span>
<span id="cb1-67"><a></a>      ylab("Count") +</span>
<span id="cb1-68"><a></a>      xlab("Well-Being Score") +</span>
<span id="cb1-69"><a></a>      #Sets the x axis ticks to cover the whole plot</span>
<span id="cb1-70"><a></a>      scale_x_continuous(</span>
<span id="cb1-71"><a></a>        limits = c(lower, upper),</span>
<span id="cb1-72"><a></a>        breaks = seq(round(lower), round(upper), by = 1)</span>
<span id="cb1-73"><a></a>      ) +</span>
<span id="cb1-74"><a></a>      #Clears the y-axis ticks</span>
<span id="cb1-75"><a></a>      scale_color_manual("aboveCutoff", values = c("#1F78B4", "#b2df8a")) +</span>
<span id="cb1-76"><a></a>      scale_fill_manual("aboveCutoff", values = c("#1F78B4", "#b2df8a")) +</span>
<span id="cb1-77"><a></a>      scale_y_continuous(breaks = NULL) +</span>
<span id="cb1-78"><a></a>      theme_bw(base_size = 20) +</span>
<span id="cb1-79"><a></a>      theme(legend.title = element_blank())</span>
<span id="cb1-80"><a></a>    #theme_minimalism()</span>
<span id="cb1-81"><a></a>  })</span>
<span id="cb1-82"><a></a>}</span>
<span id="cb1-83"><a></a></span>
<span id="cb1-84"><a></a>shinyApp(ui, server)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Try adjusting the sample mean cut-off.</p>
</section>
<section id="sampling-distribution-1" class="slide level2 smaller">
<h2>Sampling distribution</h2>
<ul>
<li>Assuming the central limit theorem holds, what shape does this distribution have?</li>
</ul>
<div class="r-stack">
<div class="fragment fade-in-then-out" data-fragment-index="2">
<p><span style="color: blue;">Normal</span>. That the sampling distribution of the mean is normal will be useful when we later conduct hypothesis testing.</p>
</div>
<div class="fragment fade-in" data-fragment-index="3">
<p><span style="color: blue;">Normal</span>. We do not need to hypothetically conduct many experiments. Given the mean and variance of the population, statisticians have figured out the shape of the sampling distribution and the proportion of means above/below any value.</p>
</div>
</div>
<div class="r-stack">
<div class="fragment fade-in" data-fragment-index="2">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-5-1.png" style="height:50.0%" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="review-normal-distribution" class="title-slide slide level1 center">
<h1>Review: Normal distribution</h1>
<p>Scroll down for a review of the normal distribution, or advance to the right to skip</p>
</section>
<section id="normal-distribution" class="slide level2">
<h2>Normal distribution</h2>
<ul>
<li>A normal distribution is a probability distribution
<ul>
<li>If scores follow a normal distribution, it tells us the probability of observing certain scores (or ranges of scores)</li>
</ul></li>
<li>The shape of a normal distribution is fully described by just two numbers:
<ul>
<li>Mean</li>
<li>Variance (or standard deviation)</li>
</ul></li>
</ul>
</section>
<section id="normal-distribution-1" class="slide level2">
<h2>Normal distribution</h2>
<p>Try changing the mean and variance to see how the distribution changes:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb2-1"><a></a>#| '!! shinylive warning !!': |</span>
<span id="cb2-2"><a></a>#|   shinylive does not work in self-contained HTML documents.</span>
<span id="cb2-3"><a></a>#|   Please set `embed-resources: false` in your metadata.</span>
<span id="cb2-4"><a></a>#| standalone: true</span>
<span id="cb2-5"><a></a>#| panel: fill</span>
<span id="cb2-6"><a></a>#| fig-align: center</span>
<span id="cb2-7"><a></a>#| viewerHeight: 650</span>
<span id="cb2-8"><a></a>library(tibble)</span>
<span id="cb2-9"><a></a>library(munsell)</span>
<span id="cb2-10"><a></a>library(shiny)</span>
<span id="cb2-11"><a></a>library(ggplot2)</span>
<span id="cb2-12"><a></a></span>
<span id="cb2-13"><a></a>ui &lt;- fluidPage(</span>
<span id="cb2-14"><a></a>  plotOutput(outputId = "normalDistPlot1"),</span>
<span id="cb2-15"><a></a>  sliderInput("normalmean", "Mean:", min = 40, max = 60, value = 50, step = 1),</span>
<span id="cb2-16"><a></a>  sliderInput("normalvar", "Variance:", min = 10, max = 40, value = 25, step = 1)</span>
<span id="cb2-17"><a></a>)</span>
<span id="cb2-18"><a></a></span>
<span id="cb2-19"><a></a>server &lt;- function(input, output){</span>
<span id="cb2-20"><a></a>  output$normalDistPlot1 &lt;- renderPlot({</span>
<span id="cb2-21"><a></a>    p &lt;- ggplot(data.frame(x = c(25, 75)), aes(x = x)) +</span>
<span id="cb2-22"><a></a>      xlim(25, 75) +</span>
<span id="cb2-23"><a></a>      ylim(0, .15) +</span>
<span id="cb2-24"><a></a>  </span>
<span id="cb2-25"><a></a>      stat_function(</span>
<span id="cb2-26"><a></a>        fun = dnorm,</span>
<span id="cb2-27"><a></a>        args = list(mean = input$normalmean, sd = sqrt(input$normalvar)),</span>
<span id="cb2-28"><a></a>        geom = "area",</span>
<span id="cb2-29"><a></a>        fill = "#b2df8a"</span>
<span id="cb2-30"><a></a>      ) +</span>
<span id="cb2-31"><a></a>      stat_function(</span>
<span id="cb2-32"><a></a>        fun = dnorm,</span>
<span id="cb2-33"><a></a>        args = list(mean = input$normalmean, sd = sqrt(input$normalvar))</span>
<span id="cb2-34"><a></a>      ) +</span>
<span id="cb2-35"><a></a>  </span>
<span id="cb2-36"><a></a>      labs(x = "\n X", y = "density \n") +</span>
<span id="cb2-37"><a></a>      theme_bw(base_size = 19)</span>
<span id="cb2-38"><a></a>    p</span>
<span id="cb2-39"><a></a>  })</span>
<span id="cb2-40"><a></a>}</span>
<span id="cb2-41"><a></a></span>
<span id="cb2-42"><a></a>shinyApp(ui, server)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="standard-normal-distribution" class="slide level2">
<h2>Standard normal distribution</h2>
<div class="r-stack">
<div class="fragment fade-out" data-fragment-index="1">
<p>A standard normal distribution is a special case of the normal distribution with:</p>
<ul>
<li>Mean = 0</li>
<li>Variance = 1 (or equivalently, standard deviation = 1)</li>
</ul>
</div>
<div class="fragment fade-in" data-fragment-index="1">
<p>A standard normal distribution is often referenced in hypothesis testing</p>
<ul>
<li>You may have seen a “Z table” that has values of this distribution with the proportion in one or both tails</li>
<li>Examples are provided on the next slides</li>
</ul>
</div>
</div>

<img data-src="index_files/figure-revealjs/unnamed-chunk-6-1.png" width="960" class="r-stretch"></section>
<section id="standard-normal-distribution-1" class="slide level2">
<h2>Standard normal distribution</h2>
<div class="r-fit-text">
<p>The table below has pairs of values:</p>
<ul>
<li>Z: a value along the x-axis of a standard normal distribution</li>
<li>prop: the proportion in the <span style="color: blue;">right-hand</span> tail of the distribution</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Z</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">prop</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Z</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">prop</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Z</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">prop</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Z</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">prop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-2.0</td>
<td style="text-align: right; border-right: 1px solid;">0.977</td>
<td style="text-align: right;">-1.0</td>
<td style="text-align: right; border-right: 1px solid;">0.841</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right; border-right: 1px solid;">0.500</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right; border-right: 1px solid;">0.159</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.9</td>
<td style="text-align: right; border-right: 1px solid;">0.971</td>
<td style="text-align: right;">-0.9</td>
<td style="text-align: right; border-right: 1px solid;">0.816</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right; border-right: 1px solid;">0.460</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right; border-right: 1px solid;">0.136</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.8</td>
<td style="text-align: right; border-right: 1px solid;">0.964</td>
<td style="text-align: right;">-0.8</td>
<td style="text-align: right; border-right: 1px solid;">0.788</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right; border-right: 1px solid;">0.421</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right; border-right: 1px solid;">0.115</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.7</td>
<td style="text-align: right; border-right: 1px solid;">0.955</td>
<td style="text-align: right;">-0.7</td>
<td style="text-align: right; border-right: 1px solid;">0.758</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right; border-right: 1px solid;">0.382</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right; border-right: 1px solid;">0.097</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.6</td>
<td style="text-align: right; border-right: 1px solid;">0.945</td>
<td style="text-align: right;">-0.6</td>
<td style="text-align: right; border-right: 1px solid;">0.726</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right; border-right: 1px solid;">0.345</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: right; border-right: 1px solid;">0.081</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.5</td>
<td style="text-align: right; border-right: 1px solid;">0.933</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right; border-right: 1px solid;">0.691</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right; border-right: 1px solid;">0.309</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right; border-right: 1px solid;">0.067</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.4</td>
<td style="text-align: right; border-right: 1px solid;">0.919</td>
<td style="text-align: right;">-0.4</td>
<td style="text-align: right; border-right: 1px solid;">0.655</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right; border-right: 1px solid;">0.274</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right; border-right: 1px solid;">0.055</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.3</td>
<td style="text-align: right; border-right: 1px solid;">0.903</td>
<td style="text-align: right;">-0.3</td>
<td style="text-align: right; border-right: 1px solid;">0.618</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right; border-right: 1px solid;">0.242</td>
<td style="text-align: right;">1.7</td>
<td style="text-align: right; border-right: 1px solid;">0.045</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.2</td>
<td style="text-align: right; border-right: 1px solid;">0.885</td>
<td style="text-align: right;">-0.2</td>
<td style="text-align: right; border-right: 1px solid;">0.579</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right; border-right: 1px solid;">0.212</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: right; border-right: 1px solid;">0.036</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.1</td>
<td style="text-align: right; border-right: 1px solid;">0.864</td>
<td style="text-align: right;">-0.1</td>
<td style="text-align: right; border-right: 1px solid;">0.540</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right; border-right: 1px solid;">0.184</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right; border-right: 1px solid;">0.029</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Example: 18.4% of the distribution greater than 0.9; thus we can infer that 81.6% of the distribution is less than 0.9.</p>
</div>
</section>
<section id="standard-normal-distribution-2" class="slide level2">
<h2>Standard normal distribution</h2>
<div class="r-fit-text">
<p>The table below has pairs of values:</p>
<ul>
<li>Z: a value along the x-axis of a standard normal distribution</li>
<li>prop: the proportion in the <span style="color: blue;">left-hand tail</span> of the distribution</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Z</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">prop</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Z</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">prop</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Z</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">prop</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Z</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">prop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-2.0</td>
<td style="text-align: right; border-right: 1px solid;">0.023</td>
<td style="text-align: right;">-1.0</td>
<td style="text-align: right; border-right: 1px solid;">0.159</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right; border-right: 1px solid;">0.500</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right; border-right: 1px solid;">0.841</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.9</td>
<td style="text-align: right; border-right: 1px solid;">0.029</td>
<td style="text-align: right;">-0.9</td>
<td style="text-align: right; border-right: 1px solid;">0.184</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right; border-right: 1px solid;">0.540</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right; border-right: 1px solid;">0.864</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.8</td>
<td style="text-align: right; border-right: 1px solid;">0.036</td>
<td style="text-align: right;">-0.8</td>
<td style="text-align: right; border-right: 1px solid;">0.212</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right; border-right: 1px solid;">0.579</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right; border-right: 1px solid;">0.885</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.7</td>
<td style="text-align: right; border-right: 1px solid;">0.045</td>
<td style="text-align: right;">-0.7</td>
<td style="text-align: right; border-right: 1px solid;">0.242</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right; border-right: 1px solid;">0.618</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right; border-right: 1px solid;">0.903</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.6</td>
<td style="text-align: right; border-right: 1px solid;">0.055</td>
<td style="text-align: right;">-0.6</td>
<td style="text-align: right; border-right: 1px solid;">0.274</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right; border-right: 1px solid;">0.655</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: right; border-right: 1px solid;">0.919</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.5</td>
<td style="text-align: right; border-right: 1px solid;">0.067</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right; border-right: 1px solid;">0.309</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right; border-right: 1px solid;">0.691</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right; border-right: 1px solid;">0.933</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.4</td>
<td style="text-align: right; border-right: 1px solid;">0.081</td>
<td style="text-align: right;">-0.4</td>
<td style="text-align: right; border-right: 1px solid;">0.345</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right; border-right: 1px solid;">0.726</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right; border-right: 1px solid;">0.945</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.3</td>
<td style="text-align: right; border-right: 1px solid;">0.097</td>
<td style="text-align: right;">-0.3</td>
<td style="text-align: right; border-right: 1px solid;">0.382</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right; border-right: 1px solid;">0.758</td>
<td style="text-align: right;">1.7</td>
<td style="text-align: right; border-right: 1px solid;">0.955</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.2</td>
<td style="text-align: right; border-right: 1px solid;">0.115</td>
<td style="text-align: right;">-0.2</td>
<td style="text-align: right; border-right: 1px solid;">0.421</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right; border-right: 1px solid;">0.788</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: right; border-right: 1px solid;">0.964</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.1</td>
<td style="text-align: right; border-right: 1px solid;">0.136</td>
<td style="text-align: right;">-0.1</td>
<td style="text-align: right; border-right: 1px solid;">0.460</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right; border-right: 1px solid;">0.816</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right; border-right: 1px solid;">0.971</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Example: 81.6% of the distribution less than 0.9; thus we can infer that 18.4% of the distribution is greater than 0.9.</p>
</div>
</section>
<section id="standard-normal-distribution-3" class="slide level2">
<h2>Standard normal distribution</h2>
<p>To visualize Z values and the proportion in the tail, change the values or tail below:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb3-1"><a></a>#| '!! shinylive warning !!': |</span>
<span id="cb3-2"><a></a>#|   shinylive does not work in self-contained HTML documents.</span>
<span id="cb3-3"><a></a>#|   Please set `embed-resources: false` in your metadata.</span>
<span id="cb3-4"><a></a>#| standalone: true</span>
<span id="cb3-5"><a></a>#| panel: fill</span>
<span id="cb3-6"><a></a>#| fig-align: center</span>
<span id="cb3-7"><a></a>#| viewerHeight: 600</span>
<span id="cb3-8"><a></a>library(tibble)</span>
<span id="cb3-9"><a></a>library(munsell)</span>
<span id="cb3-10"><a></a>library(shiny)</span>
<span id="cb3-11"><a></a>library(ggplot2)</span>
<span id="cb3-12"><a></a></span>
<span id="cb3-13"><a></a>ui &lt;- fluidPage(</span>
<span id="cb3-14"><a></a>  plotOutput(outputId = "normalDistPlot3"),</span>
<span id="cb3-15"><a></a>  numericInput(</span>
<span id="cb3-16"><a></a>    "normalcutoff2",</span>
<span id="cb3-17"><a></a>    "Z cutoff value:",</span>
<span id="cb3-18"><a></a>    min = -3,</span>
<span id="cb3-19"><a></a>    max = 3,</span>
<span id="cb3-20"><a></a>    value = 1,</span>
<span id="cb3-21"><a></a>    step = .05</span>
<span id="cb3-22"><a></a>  ),</span>
<span id="cb3-23"><a></a>  radioButtons(</span>
<span id="cb3-24"><a></a>    "normaltail2",</span>
<span id="cb3-25"><a></a>    "Choose a tail:",</span>
<span id="cb3-26"><a></a>    choices = c("Upper Tail", "Lower Tail")</span>
<span id="cb3-27"><a></a>  )</span>
<span id="cb3-28"><a></a>)</span>
<span id="cb3-29"><a></a></span>
<span id="cb3-30"><a></a>server &lt;- function(input, output){</span>
<span id="cb3-31"><a></a>  output$normalDistPlot3 &lt;- renderPlot({</span>
<span id="cb3-32"><a></a>    prop &lt;- ifelse(</span>
<span id="cb3-33"><a></a>      input$normaltail2 == "Upper Tail",</span>
<span id="cb3-34"><a></a>      round(pnorm(input$normalcutoff2, lower.tail = FALSE), 3),</span>
<span id="cb3-35"><a></a>      round(pnorm(input$normalcutoff2, lower.tail = TRUE), 3)</span>
<span id="cb3-36"><a></a>    )</span>
<span id="cb3-37"><a></a>  </span>
<span id="cb3-38"><a></a>    p &lt;- ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +</span>
<span id="cb3-39"><a></a>      xlim(-4, 4) +</span>
<span id="cb3-40"><a></a>      ylim(0, .5) +</span>
<span id="cb3-41"><a></a>  </span>
<span id="cb3-42"><a></a>      stat_function(fun = dnorm)</span>
<span id="cb3-43"><a></a>  </span>
<span id="cb3-44"><a></a>    if (input$normaltail2 == "Upper Tail") {</span>
<span id="cb3-45"><a></a>      p &lt;- p +</span>
<span id="cb3-46"><a></a>        stat_function(</span>
<span id="cb3-47"><a></a>          fun = dnorm,</span>
<span id="cb3-48"><a></a>          geom = "area",</span>
<span id="cb3-49"><a></a>          fill = "#b2df8a",</span>
<span id="cb3-50"><a></a>          xlim = c(-4, input$normalcutoff2)</span>
<span id="cb3-51"><a></a>        ) +</span>
<span id="cb3-52"><a></a>        stat_function(</span>
<span id="cb3-53"><a></a>          fun = dnorm,</span>
<span id="cb3-54"><a></a>          geom = "area",</span>
<span id="cb3-55"><a></a>          fill = "#1F78B4",</span>
<span id="cb3-56"><a></a>          xlim = c(input$normalcutoff2, 4)</span>
<span id="cb3-57"><a></a>        ) +</span>
<span id="cb3-58"><a></a>        geom_text(label = paste0("Proportion: ", prop), x = 3, y = .3)</span>
<span id="cb3-59"><a></a>    } else if (input$normaltail2 == "Lower Tail") {</span>
<span id="cb3-60"><a></a>      p &lt;- p +</span>
<span id="cb3-61"><a></a>        stat_function(</span>
<span id="cb3-62"><a></a>          fun = dnorm,</span>
<span id="cb3-63"><a></a>          geom = "area",</span>
<span id="cb3-64"><a></a>          fill = "#1F78B4",</span>
<span id="cb3-65"><a></a>          xlim = c(-4, input$normalcutoff2)</span>
<span id="cb3-66"><a></a>        ) +</span>
<span id="cb3-67"><a></a>        stat_function(</span>
<span id="cb3-68"><a></a>          fun = dnorm,</span>
<span id="cb3-69"><a></a>          geom = "area",</span>
<span id="cb3-70"><a></a>          fill = "#b2df8a",</span>
<span id="cb3-71"><a></a>          xlim = c(input$normalcutoff2, 4)</span>
<span id="cb3-72"><a></a>        ) +</span>
<span id="cb3-73"><a></a>        geom_text(label = paste0("Proportion: ", prop), x = -3, y = .3)</span>
<span id="cb3-74"><a></a>    }</span>
<span id="cb3-75"><a></a>  </span>
<span id="cb3-76"><a></a>    p &lt;- p +</span>
<span id="cb3-77"><a></a>      geom_vline(xintercept = input$normalcutoff2, color = "black") +</span>
<span id="cb3-78"><a></a>      labs(x = "\n z", y = "density \n") +</span>
<span id="cb3-79"><a></a>      theme_bw(base_size = 22) +</span>
<span id="cb3-80"><a></a>      geom_text(</span>
<span id="cb3-81"><a></a>        label = paste0("Cutoff: ", input$normalcutoff2),</span>
<span id="cb3-82"><a></a>        x = input$normalcutoff2 - .7,</span>
<span id="cb3-83"><a></a>        y = .45</span>
<span id="cb3-84"><a></a>      )</span>
<span id="cb3-85"><a></a>  </span>
<span id="cb3-86"><a></a>    p</span>
<span id="cb3-87"><a></a>  })</span>
<span id="cb3-88"><a></a>}</span>
<span id="cb3-89"><a></a></span>
<span id="cb3-90"><a></a>shinyApp(ui, server)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="learning-check" class="slide level2">
<h2>Learning check</h2>
<p>Based on either a Z-table or the app on the slide above…</p>
<div class="fragment">
<ul>
<li>What proportion of scores are above Z = 1.30?</li>
</ul>
</div>
<div class="fragment">
<p>Answer: .097 or 9.7%</p>
</div>
<div class="fragment">
<ul>
<li>What proportion of scores are below Z = -1.20?</li>
</ul>
</div>
<div class="fragment">
<p>Answer: .115 or 11.5%</p>
</div>
<div class="fragment">
<ul>
<li>What proportion of scores are between Z = -1.8 and Z = 1.8?</li>
</ul>
</div>
<div class="fragment">
<p>Answer: This one is a little more challenging. Recall that proportions range from 0 to 1; the proportion of the entire distribution is equal to 1. Since .036 is less than Z = -1.8, and .036 is above Z = 1.8, then the proportion between these two values is: 1 - .036 - .036 = .928.</p>
</div>
</section></section>
<section>
<section id="review-standardized-z-scores" class="title-slide slide level1 center">
<h1>Review: Standardized (Z) scores</h1>
<p>Scroll down for a review of standardized (Z) scores, or advance to the right to skip</p>
<!--
## Standardizing the sample mean

Suppose we obtain a sample mean of $\bar{x} = 52$

-  Is this an extreme mean or is it likely to occur under $H_0$?

<!--How does this compare to the sampling distribution under $H_0$?-->
<!--
One way to gain some insight into these questions is to standardize the sample mean

- But first, let's back up to the concept of a standardized score with an example...
-->
</section>
<section id="standardizing-a-single-score" class="slide level2">
<h2>Standardizing a single score</h2>
<p>What if we sample a single observation and obtain a score of <span class="math inline">\(X = 58\)</span>?</p>
<ul>
<li>Is that a large value? A small value?</li>
</ul>
<p>If we knew how <span class="math inline">\(X = 58\)</span> compared to other scores, we could answer such questions</p>
<ul>
<li>Standardized scores, or Z-scores, can help us compare <span class="math inline">\(X=58\)</span> to some distribution of other scores</li>
</ul>
</section>
<section id="standardized-z-scores" class="slide level2">
<h2>Standardized (Z) scores</h2>
<p>To compute a Z-score, we need to know something about the distribution of other scores:</p>
<ul>
<li>The mean</li>
<li>The standard deviation (or variance)</li>
</ul>
<p>The score can then be standardized:</p>
<p><span class="math display">\[\begin{align*}
Z = \frac{\text{score - mean}}{\text{standard deviation}}
\end{align*}\]</span></p>
</section>
<section id="standardized-z-scores-1" class="slide level2">
<h2>Standardized (Z) scores</h2>
<p>As an example, pretend:</p>
<ul>
<li><span class="math inline">\(X = 58\)</span></li>
<li>We compare <span class="math inline">\(X\)</span> to a distribution of scores with <span class="math inline">\(\text{mean} = 50\)</span> and <span class="math inline">\(\text{standard deviation} = 5\)</span></li>
</ul>
<p>Then,</p>
<p><span class="math display">\[\begin{align*}
Z = \frac{\text{score - mean}}{\text{standard deviation}} = \frac{58-50}{5} = 1.6
\end{align*}\]</span></p>
<p>To interpret the Z-score for this observation, we can say that <span class="math inline">\(X\)</span> is 1.6 standard deviations above the mean of the other scores</p>
<!-- Try computing some other z-scores? -->
</section>
<section id="standardizing-a-normal-distribution" class="slide level2">
<h2>Standardizing a normal distribution</h2>
<p>Interpreting Z-scores is easier if the entire distribution of other scores follows a normal distribution</p>
<ul>
<li>We can reference a Z-table or an app that tells us the proportion of scores below or above a particular Z-score</li>
</ul>
</section>
<section id="standard-normal-distribution-4" class="slide level2">
<h2>Standard normal distribution</h2>
<p>To visualize Z values and the proportion in the tail, change the values or tail below:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb4-1"><a></a>#| '!! shinylive warning !!': |</span>
<span id="cb4-2"><a></a>#|   shinylive does not work in self-contained HTML documents.</span>
<span id="cb4-3"><a></a>#|   Please set `embed-resources: false` in your metadata.</span>
<span id="cb4-4"><a></a>#| standalone: true</span>
<span id="cb4-5"><a></a>#| panel: fill</span>
<span id="cb4-6"><a></a>#| fig-align: center</span>
<span id="cb4-7"><a></a>#| viewerHeight: 600</span>
<span id="cb4-8"><a></a>library(tibble)</span>
<span id="cb4-9"><a></a>library(munsell)</span>
<span id="cb4-10"><a></a>library(shiny)</span>
<span id="cb4-11"><a></a>library(ggplot2)</span>
<span id="cb4-12"><a></a></span>
<span id="cb4-13"><a></a>ui &lt;- fluidPage(</span>
<span id="cb4-14"><a></a>  plotOutput(outputId = "normalDistPlot2"),</span>
<span id="cb4-15"><a></a>  numericInput(</span>
<span id="cb4-16"><a></a>    "normalcutoff",</span>
<span id="cb4-17"><a></a>    "Z cutoff value:",</span>
<span id="cb4-18"><a></a>    min = -3,</span>
<span id="cb4-19"><a></a>    max = 3,</span>
<span id="cb4-20"><a></a>    value = 1,</span>
<span id="cb4-21"><a></a>    step = .05</span>
<span id="cb4-22"><a></a>  ),</span>
<span id="cb4-23"><a></a>  radioButtons(</span>
<span id="cb4-24"><a></a>    "normaltail",</span>
<span id="cb4-25"><a></a>    "Choose a tail:",</span>
<span id="cb4-26"><a></a>    choices = c("Upper Tail", "Lower Tail")</span>
<span id="cb4-27"><a></a>  )</span>
<span id="cb4-28"><a></a>)</span>
<span id="cb4-29"><a></a></span>
<span id="cb4-30"><a></a>server &lt;- function(input, output){</span>
<span id="cb4-31"><a></a>  output$normalDistPlot2 &lt;- renderPlot({</span>
<span id="cb4-32"><a></a>    prop &lt;- ifelse(</span>
<span id="cb4-33"><a></a>      input$normaltail == "Upper Tail",</span>
<span id="cb4-34"><a></a>      round(pnorm(input$normalcutoff, lower.tail = FALSE), 3),</span>
<span id="cb4-35"><a></a>      round(pnorm(input$normalcutoff, lower.tail = TRUE), 3)</span>
<span id="cb4-36"><a></a>    )</span>
<span id="cb4-37"><a></a>  </span>
<span id="cb4-38"><a></a>    p &lt;- ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +</span>
<span id="cb4-39"><a></a>      xlim(-4, 4) +</span>
<span id="cb4-40"><a></a>      ylim(0, .5) +</span>
<span id="cb4-41"><a></a>  </span>
<span id="cb4-42"><a></a>      stat_function(fun = dnorm)</span>
<span id="cb4-43"><a></a>  </span>
<span id="cb4-44"><a></a>    if (input$normaltail == "Upper Tail") {</span>
<span id="cb4-45"><a></a>      p &lt;- p +</span>
<span id="cb4-46"><a></a>        stat_function(</span>
<span id="cb4-47"><a></a>          fun = dnorm,</span>
<span id="cb4-48"><a></a>          geom = "area",</span>
<span id="cb4-49"><a></a>          fill = "#b2df8a",</span>
<span id="cb4-50"><a></a>          xlim = c(-4, input$normalcutoff)</span>
<span id="cb4-51"><a></a>        ) +</span>
<span id="cb4-52"><a></a>        stat_function(</span>
<span id="cb4-53"><a></a>          fun = dnorm,</span>
<span id="cb4-54"><a></a>          geom = "area",</span>
<span id="cb4-55"><a></a>          fill = "#1F78B4",</span>
<span id="cb4-56"><a></a>          xlim = c(input$normalcutoff, 4)</span>
<span id="cb4-57"><a></a>        ) +</span>
<span id="cb4-58"><a></a>        geom_text(label = paste0("Proportion: ", prop), x = 3, y = .3)</span>
<span id="cb4-59"><a></a>    } else if (input$normaltail == "Lower Tail") {</span>
<span id="cb4-60"><a></a>      p &lt;- p +</span>
<span id="cb4-61"><a></a>        stat_function(</span>
<span id="cb4-62"><a></a>          fun = dnorm,</span>
<span id="cb4-63"><a></a>          geom = "area",</span>
<span id="cb4-64"><a></a>          fill = "#1F78B4",</span>
<span id="cb4-65"><a></a>          xlim = c(-4, input$normalcutoff)</span>
<span id="cb4-66"><a></a>        ) +</span>
<span id="cb4-67"><a></a>        stat_function(</span>
<span id="cb4-68"><a></a>          fun = dnorm,</span>
<span id="cb4-69"><a></a>          geom = "area",</span>
<span id="cb4-70"><a></a>          fill = "#b2df8a",</span>
<span id="cb4-71"><a></a>          xlim = c(input$normalcutoff, 4)</span>
<span id="cb4-72"><a></a>        ) +</span>
<span id="cb4-73"><a></a>        geom_text(label = paste0("Proportion: ", prop), x = -3, y = .3)</span>
<span id="cb4-74"><a></a>    }</span>
<span id="cb4-75"><a></a>  </span>
<span id="cb4-76"><a></a>    p &lt;- p +</span>
<span id="cb4-77"><a></a>      geom_vline(xintercept = input$normalcutoff, color = "black") +</span>
<span id="cb4-78"><a></a>      labs(x = "\n z", y = "density \n") +</span>
<span id="cb4-79"><a></a>      theme_bw(base_size = 22) +</span>
<span id="cb4-80"><a></a>      geom_text(</span>
<span id="cb4-81"><a></a>        label = paste0("Cutoff: ", input$normalcutoff),</span>
<span id="cb4-82"><a></a>        x = input$normalcutoff - .7,</span>
<span id="cb4-83"><a></a>        y = .45</span>
<span id="cb4-84"><a></a>      )</span>
<span id="cb4-85"><a></a>  </span>
<span id="cb4-86"><a></a>    p</span>
<span id="cb4-87"><a></a>  })</span>
<span id="cb4-88"><a></a>}</span>
<span id="cb4-89"><a></a></span>
<span id="cb4-90"><a></a>shinyApp(ui, server)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="learning-check-1" class="slide level2">
<h2>Learning check</h2>
<div class="fragment">
<ul>
<li>What proportion of scores from a normal distribution are above 1.6?</li>
</ul>
</div>
<div class="fragment">
<p>Answer: 0.055 or 5.5% of scores are above Z = 1.6</p>
</div>
<div class="fragment">
<ul>
<li>What Z score would be obtained for <span class="math inline">\(X = 45\)</span> with <span class="math inline">\(\text{mean} = 50\)</span> and <span class="math inline">\(\text{Standard deviation} = 10\)</span>?</li>
<li>What proportion of scores from a normal distribution are below this value?</li>
</ul>
</div>
<div class="fragment">
<p>Answer: <span class="math inline">\(Z = \frac{45-50}{10} = -.5\)</span>, with .309 or 30.9% of scores below this value</p>
</div>
<!--
## Standardizing the sample mean

Knowing our sample mean of $\bar{x} = 62$,

our standard deviation of $\sigma = 25$, and our $H_0$ mean of $\mu = 0$, we can standardize our sample mean via a simple formula:

$$ Z = \frac{ \bar{x} - \mu}{ \sigma } = \frac{62 - 0}{25} =  2.4 $$

A Z-score of 2.4 indicates that our observed sample mean is 2.4 standard deviations above the H0 mean.
-->
<!--
## Standardized (Z) distributions {.smaller}

In addition to the our sample mean, we treat the null distribution as being standardized as well
-->
<!--
The mean of the standardized (normal) distribution is $\mu = 0$, and its standard deviation is $\sigma = 1$

Note that even though the values have changed, the shape of the distribution remains the same.
-->
</section>
<section id="unstandardized-to-standardized" class="slide level2">
<h2>Unstandardized to Standardized</h2>
<p>Standardization does not change the relative order of a set of scores</p>
<p>To see this, the app on the next slide</p>
<ul>
<li>Simulates 20,000 values for any chosen mean and standard deviation</li>
<li>Unstandardized scores are on the left</li>
<li>Standardized scores are on the right</li>
</ul>
</section>
<section id="unstandardized-to-standardized-1" class="slide level2">
<h2>Unstandardized to Standardized</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb5-1"><a></a>#| '!! shinylive warning !!': |</span>
<span id="cb5-2"><a></a>#|   shinylive does not work in self-contained HTML documents.</span>
<span id="cb5-3"><a></a>#|   Please set `embed-resources: false` in your metadata.</span>
<span id="cb5-4"><a></a>#| standalone: true</span>
<span id="cb5-5"><a></a>#| panel: fill</span>
<span id="cb5-6"><a></a>#| fig-align: center</span>
<span id="cb5-7"><a></a>#| viewerHeight: 650</span>
<span id="cb5-8"><a></a>library(tibble)</span>
<span id="cb5-9"><a></a>library(munsell)</span>
<span id="cb5-10"><a></a>library(shiny)</span>
<span id="cb5-11"><a></a>library(ggplot2)</span>
<span id="cb5-12"><a></a></span>
<span id="cb5-13"><a></a>theme_minimalism &lt;- function(base_size = 20) {</span>
<span id="cb5-14"><a></a>  theme_minimal(base_size = base_size) + # ggplot's minimal theme hides many unnecessary features of plot</span>
<span id="cb5-15"><a></a>    theme(</span>
<span id="cb5-16"><a></a>      # make modifications to the theme</span>
<span id="cb5-17"><a></a>      panel.grid.major.y = element_blank(), # hide major grid for y axis</span>
<span id="cb5-18"><a></a>      panel.grid.minor.y = element_blank(), # hide minor grid for y axis</span>
<span id="cb5-19"><a></a>      panel.grid.major.x = element_blank(), # hide major grid for x axis</span>
<span id="cb5-20"><a></a>      panel.grid.minor.x = element_blank(), # hide minor grid for x axis</span>
<span id="cb5-21"><a></a>      #text=element_text(size=14),           # font aesthetics</span>
<span id="cb5-22"><a></a>      #axis.text=element_text(size=12),</span>
<span id="cb5-23"><a></a>      #axis.title=element_text(size=14,face="bold"))</span>
<span id="cb5-24"><a></a>      axis.title = element_text(face = "bold")</span>
<span id="cb5-25"><a></a>    )</span>
<span id="cb5-26"><a></a>}</span>
<span id="cb5-27"><a></a></span>
<span id="cb5-28"><a></a>ui &lt;- fluidPage(</span>
<span id="cb5-29"><a></a>  fluidRow(</span>
<span id="cb5-30"><a></a>    column(width = 6,</span>
<span id="cb5-31"><a></a>           plotOutput(outputId = "zScorePlot2")),</span>
<span id="cb5-32"><a></a>    column(width = 6,</span>
<span id="cb5-33"><a></a>           plotOutput(outputId = "zScorePlot3"))</span>
<span id="cb5-34"><a></a>  ),</span>
<span id="cb5-35"><a></a>  sliderInput(</span>
<span id="cb5-36"><a></a>      "mu2",</span>
<span id="cb5-37"><a></a>      "Distribution Mean",</span>
<span id="cb5-38"><a></a>      min = 40,</span>
<span id="cb5-39"><a></a>      max = 60,</span>
<span id="cb5-40"><a></a>      value = 50,</span>
<span id="cb5-41"><a></a>      step = 1</span>
<span id="cb5-42"><a></a>  ),</span>
<span id="cb5-43"><a></a>  sliderInput(</span>
<span id="cb5-44"><a></a>      "stdev2",</span>
<span id="cb5-45"><a></a>      "Distribution SD",</span>
<span id="cb5-46"><a></a>      min = 4,</span>
<span id="cb5-47"><a></a>      max = 6,</span>
<span id="cb5-48"><a></a>      value = 5,</span>
<span id="cb5-49"><a></a>      step = .25</span>
<span id="cb5-50"><a></a>  )</span>
<span id="cb5-51"><a></a>)</span>
<span id="cb5-52"><a></a></span>
<span id="cb5-53"><a></a></span>
<span id="cb5-54"><a></a>server &lt;- function(input, output){</span>
<span id="cb5-55"><a></a>  # If we were to simulate the data;</span>
<span id="cb5-56"><a></a>  # alternative is to just use dnorm</span>
<span id="cb5-57"><a></a>  datstd &lt;- reactive({</span>
<span id="cb5-58"><a></a>    set.seed(runif(1, 1000 + input$mu2 + input$stdev2, 2000))</span>
<span id="cb5-59"><a></a>    #set.seed(4567)</span>
<span id="cb5-60"><a></a>    raw = rnorm(20000, mean = input$mu2, sd = input$stdev2)</span>
<span id="cb5-61"><a></a>    standardized = scale(raw)</span>
<span id="cb5-62"><a></a>    data.frame(raw, standardized)</span>
<span id="cb5-63"><a></a>  })</span>
<span id="cb5-64"><a></a>  </span>
<span id="cb5-65"><a></a>  output$zScorePlot2 &lt;- renderPlot({</span>
<span id="cb5-66"><a></a>    lower &lt;- 50 - 3 * input$stdev2</span>
<span id="cb5-67"><a></a>    upper &lt;- 50 + 3 * input$stdev2</span>
<span id="cb5-68"><a></a>  </span>
<span id="cb5-69"><a></a>    dat &lt;- datstd()</span>
<span id="cb5-70"><a></a>    ggplot(</span>
<span id="cb5-71"><a></a>      data = dat,</span>
<span id="cb5-72"><a></a>      aes(</span>
<span id="cb5-73"><a></a>        raw,</span>
<span id="cb5-74"><a></a>        colour = "Distribution of Sample means",</span>
<span id="cb5-75"><a></a>        fill = "Distribution of Sample means"</span>
<span id="cb5-76"><a></a>      )</span>
<span id="cb5-77"><a></a>    ) +</span>
<span id="cb5-78"><a></a>      #geom_histogram(bins = length(unique(round(dat$raw,0)))) +</span>
<span id="cb5-79"><a></a>      geom_histogram(bins = 50) +</span>
<span id="cb5-80"><a></a>      annotate(</span>
<span id="cb5-81"><a></a>        "text",</span>
<span id="cb5-82"><a></a>        x = Inf,</span>
<span id="cb5-83"><a></a>        y = Inf,</span>
<span id="cb5-84"><a></a>        label = paste0(</span>
<span id="cb5-85"><a></a>          "Distribution Mean = ",</span>
<span id="cb5-86"><a></a>          input$mu2,</span>
<span id="cb5-87"><a></a>          " \n Distribution SD = ",</span>
<span id="cb5-88"><a></a>          input$stdev2</span>
<span id="cb5-89"><a></a>        ),</span>
<span id="cb5-90"><a></a>        vjust = 1,</span>
<span id="cb5-91"><a></a>        hjust = 1</span>
<span id="cb5-92"><a></a>      ) +</span>
<span id="cb5-93"><a></a>      ylab("Count") +</span>
<span id="cb5-94"><a></a>      xlab("Well-Being Score") +</span>
<span id="cb5-95"><a></a>      #Sets the x axis ticks to cover the whole plot</span>
<span id="cb5-96"><a></a>      scale_x_continuous(</span>
<span id="cb5-97"><a></a>        limits = c(lower, upper),</span>
<span id="cb5-98"><a></a>        breaks = seq(round(lower), round(upper), by = input$stdev2)</span>
<span id="cb5-99"><a></a>      ) +</span>
<span id="cb5-100"><a></a>      scale_colour_manual("Legend", values = c("#b2df8a")) +</span>
<span id="cb5-101"><a></a>      scale_fill_manual("Legend", values = c("#b2df8a")) +</span>
<span id="cb5-102"><a></a>      #Clears the y-axis ticks</span>
<span id="cb5-103"><a></a>      scale_y_continuous(breaks = NULL) +</span>
<span id="cb5-104"><a></a>      theme_minimalism() +</span>
<span id="cb5-105"><a></a>      theme(legend.position = "none") +</span>
<span id="cb5-106"><a></a>      xlim(25, 75) +</span>
<span id="cb5-107"><a></a>      ylim(0, 2200)</span>
<span id="cb5-108"><a></a>  })</span>
<span id="cb5-109"><a></a>  </span>
<span id="cb5-110"><a></a>  output$zScorePlot3 &lt;- renderPlot({</span>
<span id="cb5-111"><a></a>    lower &lt;- -3</span>
<span id="cb5-112"><a></a>    upper &lt;- 3</span>
<span id="cb5-113"><a></a>    dat &lt;- datstd()</span>
<span id="cb5-114"><a></a>    ggplot(</span>
<span id="cb5-115"><a></a>      data = dat,</span>
<span id="cb5-116"><a></a>      aes(</span>
<span id="cb5-117"><a></a>        standardized,</span>
<span id="cb5-118"><a></a>        colour = "Distribution of (Standardized) \n Sample means",</span>
<span id="cb5-119"><a></a>        fill = "Distribution of (Standardized) \n Sample means"</span>
<span id="cb5-120"><a></a>      )</span>
<span id="cb5-121"><a></a>    ) +</span>
<span id="cb5-122"><a></a>      #geom_histogram(bins = length(unique(round(dat$raw,0)))) +</span>
<span id="cb5-123"><a></a>      geom_histogram(bins = 50) +</span>
<span id="cb5-124"><a></a>      annotate(</span>
<span id="cb5-125"><a></a>        "text",</span>
<span id="cb5-126"><a></a>        x = Inf,</span>
<span id="cb5-127"><a></a>        y = Inf,</span>
<span id="cb5-128"><a></a>        label = paste0("Distribution Mean = ", 0, " \n Distribution SD = ", 1),</span>
<span id="cb5-129"><a></a>        vjust = 1,</span>
<span id="cb5-130"><a></a>        hjust = 1</span>
<span id="cb5-131"><a></a>      ) +</span>
<span id="cb5-132"><a></a>      #Clears the y-axis label</span>
<span id="cb5-133"><a></a>      ylab("Count") +</span>
<span id="cb5-134"><a></a>      xlab("Well-Being Score (Standardized)") +</span>
<span id="cb5-135"><a></a>      #Sets the x axis ticks to cover the whole plot</span>
<span id="cb5-136"><a></a>      scale_x_continuous(</span>
<span id="cb5-137"><a></a>        limits = c(lower, upper),</span>
<span id="cb5-138"><a></a>        breaks = seq(round(lower), round(upper), by = 1)</span>
<span id="cb5-139"><a></a>      ) +</span>
<span id="cb5-140"><a></a>      #Clears the y-axis ticks</span>
<span id="cb5-141"><a></a>      scale_y_continuous(breaks = NULL) +</span>
<span id="cb5-142"><a></a>      scale_colour_manual("Legend", values = c("#b2df8a")) +</span>
<span id="cb5-143"><a></a>      scale_fill_manual("Legend", values = c("#b2df8a")) +</span>
<span id="cb5-144"><a></a>      theme_minimalism() +</span>
<span id="cb5-145"><a></a>      theme(legend.position = "none") +</span>
<span id="cb5-146"><a></a>      ylim(0, 2200)</span>
<span id="cb5-147"><a></a>  })</span>
<span id="cb5-148"><a></a>}</span>
<span id="cb5-149"><a></a></span>
<span id="cb5-150"><a></a>shinyApp(ui, server)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- TODO: Could have above interactive plot have corresponding cut-offs for both distributions, with proportion in tail-->
</section>
<section id="unstandardized-to-standardized-2" class="slide level2">
<h2>Unstandardized to Standardized</h2>
<div class="fragment">
<ul>
<li>Regardless of the mean and standard deviation of the unstandardized scores, what will the mean and standard deviation be for the standardized scores?</li>
</ul>
</div>
<div class="fragment">
<p>The standardized distribution will always have a mean of 0 and standard deviation of 1</p>
</div>
</section></section>
<section id="sampling-distribution-of-barx-under-h_0" class="title-slide slide level1 h2 center">
<h1>Sampling distribution of <span class="math inline">\(\bar{x}\)</span> under <span class="math inline">\(H_0\)</span></h1>
<div class="fragment">
<ul>
<li>Under <span class="math inline">\(H_0: \mu = 50\)</span>
<ul>
<li>The <span style="color: blue;">mean</span> of the sampling distribution is 50</li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>With assumed <span class="math inline">\(\sigma^2 = 25\)</span> in the population and <span class="math inline">\(n=30\)</span>
<ul>
<li>The <span style="color: blue;">standard deviation</span> of the sampling distribution is <span class="math inline">\(\sqrt{25/n} = 5/\sqrt{30} \approx .913\)</span></li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>If the assumptions of the central limit theorem hold…
<ul>
<li>This distribution is <span style="color: blue;">normal</span></li>
</ul></li>
</ul>
</div>
</section>

<section id="sampling-distribution-of-barx-under-h_0-1" class="title-slide slide level1 h2 center">
<h1>Sampling distribution of <span class="math inline">\(\bar{x}\)</span> under <span class="math inline">\(H_0\)</span></h1>

<img data-src="index_files/figure-revealjs/unnamed-chunk-10-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>

<section id="standardizing-the-sampling-distribution" class="title-slide slide level1 center">
<h1>Standardizing the sampling distribution</h1>
<p>We will work with a standardized version of the sampling distribution under <span class="math inline">\(H_0\)</span></p>
<div class="fragment fade-in" data-fragment-index="1">
<p>For short, call this the <span class="fragment highlight-blue" data-fragment-index="1">null distribution</span></p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-11-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-12-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section id="standardizing-the-sample-mean" class="title-slide slide level1 center">
<h1>Standardizing the sample mean</h1>
<p>We also standardized the sample mean, <span class="math inline">\(\bar{x} = 52\)</span>, with respect to the mean and standard deviation (i.e., standard error) of the null distribution:</p>
<p><span class="math display">\[\begin{align*}
Z = \frac{\text{value} - \text{distribution mean}}{\text{standard deviation}} = \frac{52 - 50}{.913} = 2.19
\end{align*}\]</span></p>
<div class="fragment">
<p><span class="math inline">\(Z = 2.19\)</span> is the <span style="color: blue;">obtained test statistic</span> for our sample</p>
</div>
</section>

<section id="the-null-distribution" class="title-slide slide level1 h2 center">
<h1>The Null Distribution</h1>
<div class="center">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-13-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<p>This is the Null Sampling Distribution - what the sampling distribution would look like if <span class="math inline">\(H_0\)</span> were true.</p>
<p>Note: If this plot or any subsequent plots look odd, try refreshing the page in your web browser.</p>
</section>

<section id="the-alternative-distribution" class="title-slide slide level1 h2 center">
<h1>The Alternative Distribution</h1>
<div class="center">

</div>
<p>This is an alternative distribution - what the sampling distribution would look like if the population mean were higher than under <span class="math inline">\(H_0\)</span>.</p>
</section>

<section id="the-alternative-distribution-1" class="title-slide slide level1 h2 center">
<h1>The Alternative Distribution</h1>
<div class="center">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-15-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<p>But, in practice we do not know the true population distribution.</p>
</section>

<section id="the-alternative-distributions" class="title-slide slide level1 h2 center">
<h1>The Alternative Distribution(s)</h1>
<div class="center">

</div>
<p>To further complicate things, there are an infinite number of <em>possible</em> alternative distributions</p>
</section>

<section id="the-null-distribution-1" class="title-slide slide level1 h2 center">
<h1>The Null Distribution</h1>
<div class="center">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-17-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<p>For this reason, it is typical to conduct inference by just considering the null distribution.</p>
</section>

<section>
<section id="test-your-knowledge" class="title-slide slide level1 center">
<h1>Test your Knowledge</h1>
<p>Scroll down to test your knowledge of Null and Alternative Hypotheses.</p>
<p>Alternatively, advance to continue with the module.</p>
</section>
<section id="null-alternative-hypotheses" class="slide level2">
<h2>Null &amp; Alternative Hypotheses</h2>
<div class="fragment" data-fragment-index="1">
<ul>
<li>What do the null and alternative hypotheses represent?</li>
</ul>
</div>
<div class="fragment fade-in" data-fragment-index="2">
<p>In this example, the null hypothesis (<span class="math inline">\(H_0\)</span>) represents the idea that the population of university students have mean well-being scores of 50; any difference between our sample mean and the hypothesized value of 50 could be just due to chance.</p>
<p>The alternative hypothesis (<span class="math inline">\(H_1\)</span> or <span class="math inline">\(H_a\)</span>) represents the idea that the population of university students have mean well-being scores that are different from 50. But, the exact mean of university well-being is not specified.</p>
</div>
</section>
<section id="null-alternative-hypotheses-1" class="slide level2">
<h2>Null &amp; Alternative Hypotheses</h2>
<div class="fragment" data-fragment-index="1">
<ul>
<li>Why do we rarely know what the true population distribution is?</li>
</ul>
</div>
<div class="fragment" data-fragment-index="2">
<p>Because any attribute in our population can only be estimated/approximated based on sample data. If we could obtain the entire population’s data, then use of inferential statistics is not necessary.</p>
</div>
<div class="fragment" data-fragment-index="3">
<ul>
<li>Why are there an infinite number of alternative distributions?</li>
</ul>
</div>
<div class="fragment" data-fragment-index="4">
<p>The alternative hypothesis does not specify a specific value for the mean parameter, it only states that the mean is different than that stated under <span class="math inline">\(H_0\)</span>.</p>
</div>
</section></section>
<section id="the-big-question" class="title-slide slide level1 h2 center">
<h1>The Big Question</h1>
<div class="center">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-18-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<p>So, how do we know if this sample mean came from the null distribution, or some other distribution?</p>
</section>

<section id="null-hypothesis-significance-testing" class="title-slide slide level1 center">
<h1>Null Hypothesis Significance Testing</h1>
<ul>
<li class="fragment"><p>A common approach to answering this question is <em>Null Hypothesis Significance Testing</em></p></li>
<li class="fragment"><p>Under this approach, we define what values of the sample mean (or test statistic) would be unlikely if <span class="math inline">\(H_0\)</span> were true</p></li>
</ul>

<img data-src="index_files/figure-revealjs/unnamed-chunk-19-1.png" width="960" class="r-stretch"></section>

<section id="null-hypothesis-significance-testing-1" class="title-slide slide level1 center">
<h1>Null Hypothesis Significance Testing</h1>
<p>We examine two equivalent ways of conducting null hypothesis significance testing:</p>
<div class="fragment">
<ol type="1">
<li>Compare the critical value of a test statistic (determined in part by <span class="math inline">\(\alpha\)</span>) to the obtained test statistic from our sample</li>
</ol>
</div>
<div class="fragment">
<ol start="2" type="1">
<li>Compare <span class="math inline">\(\alpha\)</span> to the obtained <span class="math inline">\(p\)</span>-value</li>
</ol>
</div>
<div class="fragment">
<p>Both require choosing <span class="math inline">\(\alpha\)</span></p>
</div>
</section>

<section id="α" class="title-slide slide level1 h2 center">
<h1>α</h1>
<p><span class="math inline">\(\alpha\)</span> (“alpha”) is the proportion in the tail of the null distribution that we deem as unlikely to occur under <span class="math inline">\(H_0\)</span></p>
<div class="r-stack">
<div class="fragment fade-in-then-out">
<ul>
<li>The <span style="color: blue;">critical region</span> are values of the null distribution that correspond to <span class="math inline">\(\alpha\)</span></li>
</ul>
</div>
<div class="fragment">
<p>Here, our alpha value is set to .05, meaning our critical region covers 5% of the distribution.</p>
</div>
</div>
<!--
We set this probability threshold according to the *alpha* value, which determines a percentage of the distribution in the tail(s) of the distribution.-->
<div class="center">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-20-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>

<section id="critical-value-one-tailed" class="title-slide slide level1 h2 center">
<h1>Critical value (one-tailed)</h1>
<div class="r-stack">
<div class="fragment fade-in-then-out">
<p>Every <span class="math inline">\(\alpha\)</span> value has a corresponding <em>cut-off value</em> that divides the critical region from the rest of the distribution.</p>
</div>
<div class="fragment fade-in">
<p>We often call this cut-off value a <span style="color: blue;">critical value</span> for the test statistic.</p>
</div>
</div>
<div class="center">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-21-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment">
<p>In this case, 5% of the values under the distribution are greater than or equal to 1.65.</p>
</div>
</section>

<section id="critical-value-one-tailed-1" class="title-slide slide level1 center">
<h1>Critical value (one-tailed)</h1>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb6-1"><a></a>#| '!! shinylive warning !!': |</span>
<span id="cb6-2"><a></a>#|   shinylive does not work in self-contained HTML documents.</span>
<span id="cb6-3"><a></a>#|   Please set `embed-resources: false` in your metadata.</span>
<span id="cb6-4"><a></a>#| standalone: true</span>
<span id="cb6-5"><a></a>#| panel: fill</span>
<span id="cb6-6"><a></a>#| fig-align: center</span>
<span id="cb6-7"><a></a>#| viewerHeight: 600</span>
<span id="cb6-8"><a></a>library(tibble)</span>
<span id="cb6-9"><a></a>library(munsell)</span>
<span id="cb6-10"><a></a>library(shiny)</span>
<span id="cb6-11"><a></a>library(ggplot2)</span>
<span id="cb6-12"><a></a></span>
<span id="cb6-13"><a></a>ui &lt;- fluidPage(</span>
<span id="cb6-14"><a></a>  plotOutput(outputId = "alphaPlot"),</span>
<span id="cb6-15"><a></a>  sliderInput("alpha", "α:", min = .01, max = .49, value = .05, step = .01),</span>
<span id="cb6-16"><a></a>  radioButtons(</span>
<span id="cb6-17"><a></a>    "tails",</span>
<span id="cb6-18"><a></a>    "Tails:",</span>
<span id="cb6-19"><a></a>    c("1 Tail (Upper)" = "onetail_upper", "1 Tail (Lower)" = "onetail_lower"),</span>
<span id="cb6-20"><a></a>    inline = T</span>
<span id="cb6-21"><a></a>  )</span>
<span id="cb6-22"><a></a>)</span>
<span id="cb6-23"><a></a></span>
<span id="cb6-24"><a></a>server &lt;- function(input, output){</span>
<span id="cb6-25"><a></a>  theme_minimalism &lt;- function(base_size = 20) {</span>
<span id="cb6-26"><a></a>    theme_minimal(base_size = base_size) + # ggplot's minimal theme hides many unnecessary features of plot</span>
<span id="cb6-27"><a></a>      theme(</span>
<span id="cb6-28"><a></a>        # make modifications to the theme</span>
<span id="cb6-29"><a></a>        panel.grid.major.y = element_blank(), # hide major grid for y axis</span>
<span id="cb6-30"><a></a>        panel.grid.minor.y = element_blank(), # hide minor grid for y axis</span>
<span id="cb6-31"><a></a>        panel.grid.major.x = element_blank(), # hide major grid for x axis</span>
<span id="cb6-32"><a></a>        panel.grid.minor.x = element_blank(), # hide minor grid for x axis</span>
<span id="cb6-33"><a></a>        #text=element_text(size=14),           # font aesthetics</span>
<span id="cb6-34"><a></a>        #axis.text=element_text(size=12),</span>
<span id="cb6-35"><a></a>        #axis.title=element_text(size=14,face="bold"))</span>
<span id="cb6-36"><a></a>        axis.title = element_text(face = "bold")</span>
<span id="cb6-37"><a></a>      )</span>
<span id="cb6-38"><a></a>  }</span>
<span id="cb6-39"><a></a>  </span>
<span id="cb6-40"><a></a>  output$alphaPlot &lt;- renderPlot({</span>
<span id="cb6-41"><a></a>    lower &lt;- -3</span>
<span id="cb6-42"><a></a>    upper &lt;- 3</span>
<span id="cb6-43"><a></a>    mu &lt;- 0</span>
<span id="cb6-44"><a></a>    #beta_value &lt;- reactive({pnorm(-qnorm(input$alpha/2,mean=mu)) - pnorm(qnorm(input$alpha/2,mean=-mu))})</span>
<span id="cb6-45"><a></a>    #power &lt;- 1-beta_value()</span>
<span id="cb6-46"><a></a>    stdev &lt;- 1</span>
<span id="cb6-47"><a></a>    critval &lt;- switch(</span>
<span id="cb6-48"><a></a>      input$tails,</span>
<span id="cb6-49"><a></a>      "onetail_upper" = reactive({</span>
<span id="cb6-50"><a></a>        qnorm(input$alpha, mean = 0, sd = 1, lower.tail = F)</span>
<span id="cb6-51"><a></a>      }),</span>
<span id="cb6-52"><a></a>      "onetail_lower" = reactive({</span>
<span id="cb6-53"><a></a>        qnorm(input$alpha, mean = 0, sd = 1)</span>
<span id="cb6-54"><a></a>      })</span>
<span id="cb6-55"><a></a>    )</span>
<span id="cb6-56"><a></a>  </span>
<span id="cb6-57"><a></a>    #critval &lt;- 0 + critval()</span>
<span id="cb6-58"><a></a>  </span>
<span id="cb6-59"><a></a>    ggplot(data = data.frame(x = c(lower, upper)), aes(x)) +</span>
<span id="cb6-60"><a></a>      stat_function(</span>
<span id="cb6-61"><a></a>        fun = dnorm, #The Null Distribution</span>
<span id="cb6-62"><a></a>        args = list(mean = 0, sd = 1),</span>
<span id="cb6-63"><a></a>        geom = "area",</span>
<span id="cb6-64"><a></a>        linetype = "solid",</span>
<span id="cb6-65"><a></a>        fill = NA,</span>
<span id="cb6-66"><a></a>        size = 1.25,</span>
<span id="cb6-67"><a></a>        color = "#b2df8a",</span>
<span id="cb6-68"><a></a>        xlim = c(lower, upper)</span>
<span id="cb6-69"><a></a>      ) +</span>
<span id="cb6-70"><a></a>      stat_function(</span>
<span id="cb6-71"><a></a>        fun = dnorm, # The critical region</span>
<span id="cb6-72"><a></a>        args = list(mean = mu, sd = stdev),</span>
<span id="cb6-73"><a></a>        geom = "area",</span>
<span id="cb6-74"><a></a>        fill = "#1f78b4",</span>
<span id="cb6-75"><a></a>        color = "#1f78b4",</span>
<span id="cb6-76"><a></a>        alpha = .5,</span>
<span id="cb6-77"><a></a>        xlim = switch(</span>
<span id="cb6-78"><a></a>          input$tails,</span>
<span id="cb6-79"><a></a>          {</span>
<span id="cb6-80"><a></a>            "onetail_lower" = c(</span>
<span id="cb6-81"><a></a>              lower,</span>
<span id="cb6-82"><a></a>              qnorm(input$alpha, mean = 0, sd = 1, lower.tail = T)</span>
<span id="cb6-83"><a></a>            )</span>
<span id="cb6-84"><a></a>          },</span>
<span id="cb6-85"><a></a>          "onetail_upper" = c(</span>
<span id="cb6-86"><a></a>            qnorm(input$alpha, mean = 0, sd = 1, lower.tail = F),</span>
<span id="cb6-87"><a></a>            upper</span>
<span id="cb6-88"><a></a>          )</span>
<span id="cb6-89"><a></a>        )</span>
<span id="cb6-90"><a></a>      ) +</span>
<span id="cb6-91"><a></a>      #annotate("text",x=Inf,y=Inf, label = paste0("Power = ", round(power,3)), vjust = 1, hjust = 1) +</span>
<span id="cb6-92"><a></a>      annotate(</span>
<span id="cb6-93"><a></a>        "text",</span>
<span id="cb6-94"><a></a>        x = 2.5,</span>
<span id="cb6-95"><a></a>        y = .4,</span>
<span id="cb6-96"><a></a>        label = paste0("Critical Value = ", round(critval(), 3)),</span>
<span id="cb6-97"><a></a>        vjust = 1,</span>
<span id="cb6-98"><a></a>        hjust = 1</span>
<span id="cb6-99"><a></a>      ) +</span>
<span id="cb6-100"><a></a>      #Clears the y-axis label</span>
<span id="cb6-101"><a></a>      ylab("") +</span>
<span id="cb6-102"><a></a>      xlab("Standardized Well-being Score") +</span>
<span id="cb6-103"><a></a>      #Sets the x axis ticks to cover the whole plot</span>
<span id="cb6-104"><a></a>      scale_x_continuous(</span>
<span id="cb6-105"><a></a>        limits = c(lower, upper),</span>
<span id="cb6-106"><a></a>        breaks = seq(round(lower), round(upper), by = 1)</span>
<span id="cb6-107"><a></a>      ) +</span>
<span id="cb6-108"><a></a>      #Clears the y-axis ticks</span>
<span id="cb6-109"><a></a>      scale_y_continuous(breaks = NULL) +</span>
<span id="cb6-110"><a></a>      theme_minimalism()</span>
<span id="cb6-111"><a></a>  })</span>
<span id="cb6-112"><a></a>}</span>
<span id="cb6-113"><a></a></span>
<span id="cb6-114"><a></a>shinyApp(ui, server)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Try adjusting α. How does the critical value change?</p>
<p>Note that typically alpha values are set to .05 or .01.</p>
</section>

<section id="two-tailed-tests" class="title-slide slide level1 h2 center">
<h1>Two-tailed tests</h1>
<p>It’s more common not to specify a direction to the hypothesis when conducting a statistical test. We simply wish to test whether a population mean <em>differs</em> from <span class="math inline">\(H_0\)</span>.</p>
<p>The alternative hypothesis specified at the beginning of this presentation corresponds to this case:</p>
<p><span class="math display">\[H_a: \mu \ne 50\]</span></p>
<p>In this case, we use a <em>two-tailed</em> test.</p>
</section>

<section id="alpha-two-tailed-tests" class="title-slide slide level1 center">
<h1><span class="math inline">\(\alpha\)</span>, Two-tailed tests</h1>
<div class="center">
<div class="cell panel-fill">

</div>
</div>
<p>For two tailed-tests, our alpha value represents the <em>combined</em> percentage of the distribution in <em>both</em> tails of the distribution.</p>
<div class="r-stack">
<div class="fragment fade-in-then-out">
<p>Here, our alpha value is .05, so the lower critical region covers 2.5% of the distribution, and the upper critical region covers 2.5% of the distribution.</p>
</div>
<div class="fragment">
<p>The critical values dividing the lower and upper 2.5% of the distribution correspond to -1.96 and 1.96.</p>
</div>
</div>
</section>

<section id="critical-values-two-tailed" class="title-slide slide level1 center">
<h1>Critical values (two-tailed)</h1>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb7-1"><a></a>#| '!! shinylive warning !!': |</span>
<span id="cb7-2"><a></a>#|   shinylive does not work in self-contained HTML documents.</span>
<span id="cb7-3"><a></a>#|   Please set `embed-resources: false` in your metadata.</span>
<span id="cb7-4"><a></a>#| standalone: true</span>
<span id="cb7-5"><a></a>#| panel: fill</span>
<span id="cb7-6"><a></a>#| fig-align: center</span>
<span id="cb7-7"><a></a>#| viewerHeight: 600</span>
<span id="cb7-8"><a></a>library(tibble)</span>
<span id="cb7-9"><a></a>library(munsell)</span>
<span id="cb7-10"><a></a>library(shiny)</span>
<span id="cb7-11"><a></a>library(ggplot2)</span>
<span id="cb7-12"><a></a></span>
<span id="cb7-13"><a></a>ui &lt;- fluidPage(</span>
<span id="cb7-14"><a></a>  plotOutput(outputId = "alphaPlotTwoTail"),</span>
<span id="cb7-15"><a></a>  sliderInput("alpha", "α:", min = .01, max = .99, value = .05, step = .01)  </span>
<span id="cb7-16"><a></a>)</span>
<span id="cb7-17"><a></a></span>
<span id="cb7-18"><a></a>server &lt;- function(input, output){</span>
<span id="cb7-19"><a></a>  theme_minimalism &lt;- function(base_size = 20) {</span>
<span id="cb7-20"><a></a>    theme_minimal(base_size = base_size) + # ggplot's minimal theme hides many unnecessary features of plot</span>
<span id="cb7-21"><a></a>      theme(</span>
<span id="cb7-22"><a></a>        # make modifications to the theme</span>
<span id="cb7-23"><a></a>        panel.grid.major.y = element_blank(), # hide major grid for y axis</span>
<span id="cb7-24"><a></a>        panel.grid.minor.y = element_blank(), # hide minor grid for y axis</span>
<span id="cb7-25"><a></a>        panel.grid.major.x = element_blank(), # hide major grid for x axis</span>
<span id="cb7-26"><a></a>        panel.grid.minor.x = element_blank(), # hide minor grid for x axis</span>
<span id="cb7-27"><a></a>        #text=element_text(size=14),           # font aesthetics</span>
<span id="cb7-28"><a></a>        #axis.text=element_text(size=12),</span>
<span id="cb7-29"><a></a>        #axis.title=element_text(size=14,face="bold"))</span>
<span id="cb7-30"><a></a>        axis.title = element_text(face = "bold")</span>
<span id="cb7-31"><a></a>      )</span>
<span id="cb7-32"><a></a>  }</span>
<span id="cb7-33"><a></a>  </span>
<span id="cb7-34"><a></a>  output$alphaPlotTwoTail &lt;- renderPlot({</span>
<span id="cb7-35"><a></a>    lower &lt;- -3</span>
<span id="cb7-36"><a></a>    upper &lt;- 3</span>
<span id="cb7-37"><a></a>    mu &lt;- 0</span>
<span id="cb7-38"><a></a>    #beta_value &lt;- reactive({pnorm(-qnorm(input$alpha/2,mean=mu)) - pnorm(qnorm(input$alpha/2,mean=-mu))})</span>
<span id="cb7-39"><a></a>    #power &lt;- 1-beta_value()</span>
<span id="cb7-40"><a></a>    stdev &lt;- 1</span>
<span id="cb7-41"><a></a>  </span>
<span id="cb7-42"><a></a>    ggplot(data = data.frame(x = c(lower, upper)), aes(x)) +</span>
<span id="cb7-43"><a></a>      stat_function(</span>
<span id="cb7-44"><a></a>        fun = dnorm, #The Null Distribution</span>
<span id="cb7-45"><a></a>        args = list(mean = 0, sd = 1),</span>
<span id="cb7-46"><a></a>        geom = "area",</span>
<span id="cb7-47"><a></a>        linetype = "solid",</span>
<span id="cb7-48"><a></a>        fill = NA,</span>
<span id="cb7-49"><a></a>        size = 1.25,</span>
<span id="cb7-50"><a></a>        color = "#b2df8a",</span>
<span id="cb7-51"><a></a>        xlim = c(lower, upper)</span>
<span id="cb7-52"><a></a>      ) +</span>
<span id="cb7-53"><a></a>      stat_function(</span>
<span id="cb7-54"><a></a>        fun = dnorm, # The upper critical region</span>
<span id="cb7-55"><a></a>        args = list(mean = mu, sd = stdev),</span>
<span id="cb7-56"><a></a>        geom = "area",</span>
<span id="cb7-57"><a></a>        fill = "#1f78b4",</span>
<span id="cb7-58"><a></a>        color = "#1f78b4",</span>
<span id="cb7-59"><a></a>        alpha = .5,</span>
<span id="cb7-60"><a></a>        xlim = c(qnorm(input$alpha / 2, mean = 0, sd = 1, lower.tail = F), upper)</span>
<span id="cb7-61"><a></a>      ) +</span>
<span id="cb7-62"><a></a>      stat_function(</span>
<span id="cb7-63"><a></a>        fun = dnorm, # The lower critical region</span>
<span id="cb7-64"><a></a>        args = list(mean = mu, sd = stdev),</span>
<span id="cb7-65"><a></a>        geom = "area",</span>
<span id="cb7-66"><a></a>        fill = "#1f78b4",</span>
<span id="cb7-67"><a></a>        color = "#1f78b4",</span>
<span id="cb7-68"><a></a>        alpha = .5,</span>
<span id="cb7-69"><a></a>        xlim = c(lower, qnorm(input$alpha / 2, mean = 0, sd = 1))</span>
<span id="cb7-70"><a></a>      ) +</span>
<span id="cb7-71"><a></a>      #annotate("text",x=Inf,y=Inf, label = paste0("Power = ", round(power,3)), vjust = 1, hjust = 1) +</span>
<span id="cb7-72"><a></a>      annotate(</span>
<span id="cb7-73"><a></a>        "text",</span>
<span id="cb7-74"><a></a>        x = 2,</span>
<span id="cb7-75"><a></a>        y = .2,</span>
<span id="cb7-76"><a></a>        label = paste0(</span>
<span id="cb7-77"><a></a>          "Critical Value = +/-",</span>
<span id="cb7-78"><a></a>          round(qnorm(input$alpha / 2, mean = 0, sd = 1, lower.tail = F), 3)</span>
<span id="cb7-79"><a></a>        ),</span>
<span id="cb7-80"><a></a>        vjust = 1,</span>
<span id="cb7-81"><a></a>        hjust = 1</span>
<span id="cb7-82"><a></a>      ) +</span>
<span id="cb7-83"><a></a>      scale_colour_manual(</span>
<span id="cb7-84"><a></a>        "Legend",</span>
<span id="cb7-85"><a></a>        values = c("Null Distribution" = "#b2df8a", "Critical Region" = "#1f78b4")</span>
<span id="cb7-86"><a></a>      ) +</span>
<span id="cb7-87"><a></a>      #Clears the y-axis label</span>
<span id="cb7-88"><a></a>      ylab("") +</span>
<span id="cb7-89"><a></a>      xlab("Well-Being Score") +</span>
<span id="cb7-90"><a></a>      #Sets the x axis ticks to cover the whole plot</span>
<span id="cb7-91"><a></a>      scale_x_continuous(</span>
<span id="cb7-92"><a></a>        limits = c(lower, upper),</span>
<span id="cb7-93"><a></a>        breaks = seq(round(lower), round(upper), by = 1)</span>
<span id="cb7-94"><a></a>      ) +</span>
<span id="cb7-95"><a></a>      #Clears the y-axis ticks</span>
<span id="cb7-96"><a></a>      scale_y_continuous(breaks = NULL) +</span>
<span id="cb7-97"><a></a>      theme_minimalism()</span>
<span id="cb7-98"><a></a>  })  </span>
<span id="cb7-99"><a></a>}</span>
<span id="cb7-100"><a></a></span>
<span id="cb7-101"><a></a>shinyApp(ui, server)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Try adjusting α. How does the critical value change?</p>
<p>Note that typically alpha values are set to .05 or .01.</p>
</section>

<section id="components-of-null-hypothesis-significance-testing" class="title-slide slide level1 center">
<h1>Components of null hypothesis significance testing</h1>
<p>At this point…</p>
<ul>
<li>We choose <span class="math inline">\(\alpha\)</span></li>
<li>Our choice of <span class="math inline">\(\alpha\)</span> implies a critical value for the null distribution under <span class="math inline">\(H_0\)</span></li>
</ul>
<p>We do not require looking at the sample data to determine the above values.</p>
</section>

<section id="components-of-null-hypothesis-significance-testing-1" class="title-slide slide level1 center">
<h1>Components of null hypothesis significance testing</h1>
<p>Based on the sample data, we can compute…</p>
<ul>
<li>The obtained test statistic</li>
<li>The <span class="math inline">\(p\)</span>-value corresponding to the obtained test statistic</li>
</ul>
<p>Over then next slides, we show how to perform inference regarding <span class="math inline">\(H_0\)</span> by doing one of the following:</p>
<div class="fragment">
<ol type="1">
<li>Compare the critical value of a test statistic to the obtained test statistic from our sample</li>
</ol>
</div>
<div class="fragment">
<ol start="2" type="1">
<li>Compare <span class="math inline">\(\alpha\)</span> to the obtained <span class="math inline">\(p\)</span>-value</li>
</ol>
</div>
</section>

<section id="comparing-critical-value-to-obtained-test-statistic" class="title-slide slide level1 center">
<h1>Comparing critical value to obtained test statistic</h1>
<p>Since every <span class="math inline">\(\alpha\)</span> corresponds to a particular critical value, we can do inference by comparing the critical value to the obtained test statistic</p>
<ul>
<li class="fragment">If the <span style="color: blue;">obtained test statistic is more extreme than its critical value</span>…
<ul>
<li class="fragment">We <span style="color: blue;">reject <span class="math inline">\(H_0\)</span></span> because it is unlikely that this result would be observed if <span class="math inline">\(H_0\)</span> were true</li>
</ul></li>
<li class="fragment">If the <span style="color: blue;">obtained test statistic is less extreme than its critical value</span>…
<ul>
<li class="fragment">We <span style="color: blue;">fail to reject <span class="math inline">\(H_0\)</span></span> because this result could reasonably be observed if <span class="math inline">\(H_0\)</span> were true</li>
</ul></li>
</ul>
</section>

<section id="comparing-critical-value-to-obtained-test-statistic-1" class="title-slide slide level1 center">
<h1>Comparing critical value to obtained test statistic</h1>

<img data-src="index_files/figure-revealjs/unnamed-chunk-23-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><div class="fragment">
<p>In this case, the obtained test statistic of <span class="math inline">\(Z = 2.19\)</span> is more extreme than the critical value (when <span class="math inline">\(\alpha=.05\)</span>) of <span class="math inline">\(\pm 1.96\)</span>. This means we reject <span class="math inline">\(H_0\)</span>.</p>
</div>
</section>

<section id="comparing-alpha-to-the-p-value" class="title-slide slide level1 center">
<h1>Comparing <span class="math inline">\(\alpha\)</span> to the <span class="math inline">\(p\)</span>-value</h1>
<ul>
<li class="fragment"><p>Essentially we ask ourselves: “If <span class="math inline">\(H_0\)</span> is true, what’s the probability of getting a sample mean this extreme (or more extreme)?”</p></li>
<li class="fragment"><p>Equivalently: “If <span class="math inline">\(H_0\)</span> is true, what’s the probability of getting an obtained test statistic (e.g., Z) this extreme (or more extreme)?”</p></li>
<li class="fragment"><p>This probability is the <span style="color: blue;"><span class="math inline">\(p\)</span>-value</span> associated with our test of <span class="math inline">\(H_0\)</span></p></li>
</ul>
</section>

<section id="comparing-alpha-to-a-p-value" class="title-slide slide level1 center">
<h1>Comparing <span class="math inline">\(\alpha\)</span> to a <span class="math inline">\(p\)</span>-value</h1>
<ul>
<li class="fragment">If the <span style="color: blue;"><span class="math inline">\(p\)</span>-value is smaller than <span class="math inline">\(\alpha\)</span></span>…
<ul>
<li class="fragment">We <span style="color: blue;">reject <span class="math inline">\(H_0\)</span></span> because it is unlikely that this result would be observed if <span class="math inline">\(H_0\)</span> were true</li>
</ul></li>
<li class="fragment">If the <span style="color: blue;"><span class="math inline">\(p\)</span>-value is greater than <span class="math inline">\(\alpha\)</span></span>…
<ul>
<li class="fragment">We <span style="color: blue;">fail to reject <span class="math inline">\(H_0\)</span></span> because this result could reasonably be observed if <span class="math inline">\(H_0\)</span> were true</li>
</ul></li>
</ul>
</section>

<section id="comparing-alpha-to-a-p-value-1" class="title-slide slide level1 center">
<h1>Comparing <span class="math inline">\(\alpha\)</span> to a <span class="math inline">\(p\)</span>-value</h1>
<div class="r-stack">
<div class="fragment fade-in-then-out">
<p>In this case, our observed test statistic is <span class="math inline">\(Z = 2.19\)</span>; Only 1.43% or .0143 of the distribution has a score of 2.19 or higher.</p>
</div>
<div class="fragment fade-in-then-out">
<p>Since we are considering a two-tailed test, we also consider the proportion below <span class="math inline">\(-Z\)</span>, or below <span class="math inline">\(Z = -2.19\)</span>. This proportion is also 1.43% or .0143.</p>
</div>
<div class="fragment fade-in">
<p>The <span class="math inline">\(p\)</span>-value is therefore <span class="math inline">\(p = .0143 + .0143 = .0286\)</span>. Only 2.85% of the distribution corresponds to a Z statistic as or more extreme than 2.19 or -2.19.</p>
</div>
</div>
<div class="center">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-24-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="r-stack">
<div class="fragment fade-in-then-out">
<p>.0286 is the <span class="math inline">\(p\)</span>-value associated with our test of <span class="math inline">\(H_0\)</span>. It is the proportion beyond the obtained test statistic of <span class="math inline">\(Z=2.19\)</span>, two-tailed.</p>
</div>
<div class="fragment">
<p>Since .0286 is below our <span class="math inline">\(\alpha\)</span> value of .05, we reject <span class="math inline">\(H_0: \mu = 50\)</span> and conclude that the mean of university students is (statistically) significantly different than 50.</p>
</div>
</div>
</section>

<section id="remaining-questions" class="title-slide slide level1 center">
<h1>Remaining questions</h1>
<p>For the next few slides, consider the following questions:</p>
<ul>
<li><p>What is the relationship between a <span class="math inline">\(p\)</span>-value and its obtained test statistic?</p></li>
<li><p>What is the relationship between <span class="math inline">\(\alpha\)</span> and its critical value?</p></li>
<li><p>What are the similarities and differences between <span class="math inline">\(\alpha\)</span> and a <span class="math inline">\(p\)</span>-value?</p></li>
<li><p>What are the similarities and differences between a critical value and an obtained test statistic?</p></li>
</ul>
</section>

<section id="change-the-test-statistic-and-p-value" class="title-slide slide level1 center">
<h1>Change the test statistic and <span class="math inline">\(p\)</span>-value</h1>
<ul>
<li>Suppose <span class="math inline">\(\alpha = .05\)</span> with a critical value of 1.65</li>
<li>What happens if the test statistic changes? (e.g., a different sample mean)</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb8-1"><a></a>#| '!! shinylive warning !!': |</span>
<span id="cb8-2"><a></a>#|   shinylive does not work in self-contained HTML documents.</span>
<span id="cb8-3"><a></a>#|   Please set `embed-resources: false` in your metadata.</span>
<span id="cb8-4"><a></a>#| standalone: true</span>
<span id="cb8-5"><a></a>#| panel: fill</span>
<span id="cb8-6"><a></a>#| fig-align: center</span>
<span id="cb8-7"><a></a>#| viewerHeight: 600</span>
<span id="cb8-8"><a></a>library(tibble)</span>
<span id="cb8-9"><a></a>library(munsell)</span>
<span id="cb8-10"><a></a>library(shiny)</span>
<span id="cb8-11"><a></a>library(ggplot2)</span>
<span id="cb8-12"><a></a></span>
<span id="cb8-13"><a></a>ui &lt;- fluidPage(</span>
<span id="cb8-14"><a></a>  plotOutput(outputId = "sampleMeanPlot1"),</span>
<span id="cb8-15"><a></a>  fluidRow(</span>
<span id="cb8-16"><a></a>    column(width = 4, </span>
<span id="cb8-17"><a></a>      sliderInput(</span>
<span id="cb8-18"><a></a>      "sampleMean1",</span>
<span id="cb8-19"><a></a>      "Sample Mean (Standardized):",</span>
<span id="cb8-20"><a></a>      min = -2.6,</span>
<span id="cb8-21"><a></a>      max = 2.6,</span>
<span id="cb8-22"><a></a>      value = 2.4,</span>
<span id="cb8-23"><a></a>      step = .1</span>
<span id="cb8-24"><a></a>      )),</span>
<span id="cb8-25"><a></a>    column(width = 4,</span>
<span id="cb8-26"><a></a>      checkboxInput("shadealpha1", "Shade critical region (alpha)", value = TRUE),</span>
<span id="cb8-27"><a></a>      checkboxInput("shadep1", "Shade p-value area", value = FALSE))</span>
<span id="cb8-28"><a></a>  )</span>
<span id="cb8-29"><a></a>)</span>
<span id="cb8-30"><a></a></span>
<span id="cb8-31"><a></a>server &lt;- function(input, output){</span>
<span id="cb8-32"><a></a>  theme_minimalism &lt;- function(base_size = 20) {</span>
<span id="cb8-33"><a></a>    theme_minimal(base_size = base_size) + # ggplot's minimal theme hides many unnecessary features of plot</span>
<span id="cb8-34"><a></a>      theme(</span>
<span id="cb8-35"><a></a>        # make modifications to the theme</span>
<span id="cb8-36"><a></a>        panel.grid.major.y = element_blank(), # hide major grid for y axis</span>
<span id="cb8-37"><a></a>        panel.grid.minor.y = element_blank(), # hide minor grid for y axis</span>
<span id="cb8-38"><a></a>        panel.grid.major.x = element_blank(), # hide major grid for x axis</span>
<span id="cb8-39"><a></a>        panel.grid.minor.x = element_blank(), # hide minor grid for x axis</span>
<span id="cb8-40"><a></a>        #text=element_text(size=14),           # font aesthetics</span>
<span id="cb8-41"><a></a>        #axis.text=element_text(size=12),</span>
<span id="cb8-42"><a></a>        #axis.title=element_text(size=14,face="bold"))</span>
<span id="cb8-43"><a></a>        axis.title = element_text(face = "bold")</span>
<span id="cb8-44"><a></a>      )</span>
<span id="cb8-45"><a></a>  }</span>
<span id="cb8-46"><a></a>  </span>
<span id="cb8-47"><a></a>  output$sampleMeanPlot1 &lt;- renderPlot({</span>
<span id="cb8-48"><a></a>    twotailed &lt;- TRUE</span>
<span id="cb8-49"><a></a>    lower &lt;- -3</span>
<span id="cb8-50"><a></a>    upper &lt;- 3</span>
<span id="cb8-51"><a></a>    mu &lt;- 0</span>
<span id="cb8-52"><a></a>    stdev &lt;- 1</span>
<span id="cb8-53"><a></a>  </span>
<span id="cb8-54"><a></a>    if (twotailed) {</span>
<span id="cb8-55"><a></a>      prop &lt;- .05 / 2</span>
<span id="cb8-56"><a></a>    } else {</span>
<span id="cb8-57"><a></a>      prop &lt;- .05</span>
<span id="cb8-58"><a></a>    }</span>
<span id="cb8-59"><a></a>  </span>
<span id="cb8-60"><a></a>    plt &lt;- ggplot(data = data.frame(x = c(lower, upper)), aes(x)) +</span>
<span id="cb8-61"><a></a>      stat_function(</span>
<span id="cb8-62"><a></a>        fun = dnorm, #The Null Distribution</span>
<span id="cb8-63"><a></a>        args = list(mean = 0, sd = 1),</span>
<span id="cb8-64"><a></a>        geom = "area",</span>
<span id="cb8-65"><a></a>        linetype = "solid",</span>
<span id="cb8-66"><a></a>        fill = NA,</span>
<span id="cb8-67"><a></a>        size = 1.25,</span>
<span id="cb8-68"><a></a>        color = "#b2df8a",</span>
<span id="cb8-69"><a></a>        xlim = c(lower, upper)</span>
<span id="cb8-70"><a></a>      ) +</span>
<span id="cb8-71"><a></a>      geom_vline(xintercept = input$sampleMean1, alpha = .5) +</span>
<span id="cb8-72"><a></a>      annotate(</span>
<span id="cb8-73"><a></a>        "text",</span>
<span id="cb8-74"><a></a>        x = input$sampleMean1 - .5,</span>
<span id="cb8-75"><a></a>        y = .26,</span>
<span id="cb8-76"><a></a>        label = paste0("Standardized sample mean \n Z = ", input$sampleMean1)</span>
<span id="cb8-77"><a></a>      )</span>
<span id="cb8-78"><a></a>  </span>
<span id="cb8-79"><a></a>    if (input$shadealpha1) {</span>
<span id="cb8-80"><a></a>      plt &lt;- plt +</span>
<span id="cb8-81"><a></a>        stat_function(</span>
<span id="cb8-82"><a></a>          fun = dnorm, # The critical region</span>
<span id="cb8-83"><a></a>          args = list(mean = mu, sd = stdev),</span>
<span id="cb8-84"><a></a>          geom = "area",</span>
<span id="cb8-85"><a></a>          fill = "#1f78b4",</span>
<span id="cb8-86"><a></a>          aes(color = "Critical Region (alpha)"),</span>
<span id="cb8-87"><a></a>          #color="#1f78b4",</span>
<span id="cb8-88"><a></a>          alpha = .25,</span>
<span id="cb8-89"><a></a>          xlim = {</span>
<span id="cb8-90"><a></a>            c(qnorm(prop, mean = 0, sd = 1, lower.tail = F), upper)</span>
<span id="cb8-91"><a></a>          }</span>
<span id="cb8-92"><a></a>        )</span>
<span id="cb8-93"><a></a>      if (twotailed) {</span>
<span id="cb8-94"><a></a>        plt &lt;- plt +</span>
<span id="cb8-95"><a></a>          stat_function(</span>
<span id="cb8-96"><a></a>            fun = dnorm, # The critical region</span>
<span id="cb8-97"><a></a>            args = list(mean = mu, sd = stdev),</span>
<span id="cb8-98"><a></a>            geom = "area",</span>
<span id="cb8-99"><a></a>            fill = "#1f78b4",</span>
<span id="cb8-100"><a></a>            aes(color = "Critical Region (alpha)"),</span>
<span id="cb8-101"><a></a>            #color="#1f78b4",</span>
<span id="cb8-102"><a></a>            alpha = .25,</span>
<span id="cb8-103"><a></a>            xlim = {</span>
<span id="cb8-104"><a></a>              c(lower, qnorm(prop, mean = 0, sd = 1, lower.tail = T))</span>
<span id="cb8-105"><a></a>            }</span>
<span id="cb8-106"><a></a>          )</span>
<span id="cb8-107"><a></a>      }</span>
<span id="cb8-108"><a></a>    }</span>
<span id="cb8-109"><a></a>  </span>
<span id="cb8-110"><a></a>    if (input$shadep1) {</span>
<span id="cb8-111"><a></a>      if (twotailed) {</span>
<span id="cb8-112"><a></a>        plt &lt;- plt +</span>
<span id="cb8-113"><a></a>          stat_function(</span>
<span id="cb8-114"><a></a>            fun = dnorm, # The p-value</span>
<span id="cb8-115"><a></a>            args = list(mean = 0, sd = 1),</span>
<span id="cb8-116"><a></a>            geom = "area",</span>
<span id="cb8-117"><a></a>            linetype = "solid",</span>
<span id="cb8-118"><a></a>            fill = "#E69F00",</span>
<span id="cb8-119"><a></a>            aes(color = "p-value"),</span>
<span id="cb8-120"><a></a>            alpha = .35,</span>
<span id="cb8-121"><a></a>            xlim = c(abs(input$sampleMean1), 3)</span>
<span id="cb8-122"><a></a>          )</span>
<span id="cb8-123"><a></a>        plt &lt;- plt +</span>
<span id="cb8-124"><a></a>          stat_function(</span>
<span id="cb8-125"><a></a>            fun = dnorm, # The p-value</span>
<span id="cb8-126"><a></a>            args = list(mean = 0, sd = 1),</span>
<span id="cb8-127"><a></a>            geom = "area",</span>
<span id="cb8-128"><a></a>            linetype = "solid",</span>
<span id="cb8-129"><a></a>            fill = "#E69F00",</span>
<span id="cb8-130"><a></a>            aes(color = "p-value"),</span>
<span id="cb8-131"><a></a>            alpha = .35,</span>
<span id="cb8-132"><a></a>            xlim = c(-3, -abs(input$sampleMean1))</span>
<span id="cb8-133"><a></a>          )</span>
<span id="cb8-134"><a></a>      } else {</span>
<span id="cb8-135"><a></a>        plt &lt;- plt +</span>
<span id="cb8-136"><a></a>          stat_function(</span>
<span id="cb8-137"><a></a>            fun = dnorm, # The p-value</span>
<span id="cb8-138"><a></a>            args = list(mean = 0, sd = 1),</span>
<span id="cb8-139"><a></a>            geom = "area",</span>
<span id="cb8-140"><a></a>            linetype = "solid",</span>
<span id="cb8-141"><a></a>            fill = "#E69F00",</span>
<span id="cb8-142"><a></a>            aes(color = "p-value"),</span>
<span id="cb8-143"><a></a>            alpha = .35,</span>
<span id="cb8-144"><a></a>            xlim = c(input$sampleMean1, 3)</span>
<span id="cb8-145"><a></a>          )</span>
<span id="cb8-146"><a></a>      }</span>
<span id="cb8-147"><a></a>    }</span>
<span id="cb8-148"><a></a>  </span>
<span id="cb8-149"><a></a>    if (twotailed) {</span>
<span id="cb8-150"><a></a>      obtpval &lt;- pnorm(</span>
<span id="cb8-151"><a></a>        abs(input$sampleMean1),</span>
<span id="cb8-152"><a></a>        mean = mu,</span>
<span id="cb8-153"><a></a>        sd = stdev,</span>
<span id="cb8-154"><a></a>        lower.tail = F</span>
<span id="cb8-155"><a></a>      ) *</span>
<span id="cb8-156"><a></a>        2</span>
<span id="cb8-157"><a></a>      sig &lt;- ifelse(obtpval &lt; .05, "Significant", "Not Significant (n.s.)")</span>
<span id="cb8-158"><a></a>      plt &lt;- plt +</span>
<span id="cb8-159"><a></a>        annotate(</span>
<span id="cb8-160"><a></a>          "text",</span>
<span id="cb8-161"><a></a>          x = 2.3,</span>
<span id="cb8-162"><a></a>          y = .37,</span>
<span id="cb8-163"><a></a>          label = paste0(sig, ",\n p = ", round(obtpval, 3)),</span>
<span id="cb8-164"><a></a>          vjust = 1,</span>
<span id="cb8-165"><a></a>          hjust = 1</span>
<span id="cb8-166"><a></a>        )</span>
<span id="cb8-167"><a></a>    } else {</span>
<span id="cb8-168"><a></a>      plt &lt;- plt +</span>
<span id="cb8-169"><a></a>        annotate(</span>
<span id="cb8-170"><a></a>          "text",</span>
<span id="cb8-171"><a></a>          x = 2.3,</span>
<span id="cb8-172"><a></a>          y = .37,</span>
<span id="cb8-173"><a></a>          label = paste0(</span>
<span id="cb8-174"><a></a>            if (</span>
<span id="cb8-175"><a></a>              input$sampleMean1 &gt; qnorm(prob, mean = 0, sd = 1, lower.tail = F)</span>
<span id="cb8-176"><a></a>            ) {</span>
<span id="cb8-177"><a></a>              "Significant"</span>
<span id="cb8-178"><a></a>            } else {</span>
<span id="cb8-179"><a></a>              "Not Significant (n.s.)"</span>
<span id="cb8-180"><a></a>            },</span>
<span id="cb8-181"><a></a>            ",\n p = ",</span>
<span id="cb8-182"><a></a>            round(</span>
<span id="cb8-183"><a></a>              pnorm(input$sampleMean1, mean = mu, sd = stdev, lower.tail = F),</span>
<span id="cb8-184"><a></a>              3</span>
<span id="cb8-185"><a></a>            )</span>
<span id="cb8-186"><a></a>          ),</span>
<span id="cb8-187"><a></a>          vjust = 1,</span>
<span id="cb8-188"><a></a>          hjust = 1</span>
<span id="cb8-189"><a></a>        )</span>
<span id="cb8-190"><a></a>    }</span>
<span id="cb8-191"><a></a>  </span>
<span id="cb8-192"><a></a>    plt &lt;- plt +</span>
<span id="cb8-193"><a></a>      #Clears the y-axis label</span>
<span id="cb8-194"><a></a>      ylab("") +</span>
<span id="cb8-195"><a></a>      xlab("Well-Being Score") +</span>
<span id="cb8-196"><a></a>      #Sets the x axis ticks to cover the whole plot</span>
<span id="cb8-197"><a></a>      scale_x_continuous(</span>
<span id="cb8-198"><a></a>        limits = c(lower, upper),</span>
<span id="cb8-199"><a></a>        breaks = seq(round(lower), round(upper), by = 1)</span>
<span id="cb8-200"><a></a>      ) +</span>
<span id="cb8-201"><a></a>      #Clears the y-axis ticks</span>
<span id="cb8-202"><a></a>      scale_y_continuous(breaks = NULL) +</span>
<span id="cb8-203"><a></a>      theme_minimalism()</span>
<span id="cb8-204"><a></a>  </span>
<span id="cb8-205"><a></a>    if (input$shadep1) {</span>
<span id="cb8-206"><a></a>      plt &lt;- plt +</span>
<span id="cb8-207"><a></a>        scale_colour_manual(</span>
<span id="cb8-208"><a></a>          "Legend",</span>
<span id="cb8-209"><a></a>          values = c(</span>
<span id="cb8-210"><a></a>            "Null Distribution" = "#b2df8a",</span>
<span id="cb8-211"><a></a>            "Critical Region (alpha)" = "#1f78b4",</span>
<span id="cb8-212"><a></a>            "p-value" = "#E69F00"</span>
<span id="cb8-213"><a></a>          )</span>
<span id="cb8-214"><a></a>        )</span>
<span id="cb8-215"><a></a>    } else {</span>
<span id="cb8-216"><a></a>      plt &lt;- plt +</span>
<span id="cb8-217"><a></a>        scale_colour_manual(</span>
<span id="cb8-218"><a></a>          "Legend",</span>
<span id="cb8-219"><a></a>          values = c(</span>
<span id="cb8-220"><a></a>            "Null Distribution" = "#b2df8a",</span>
<span id="cb8-221"><a></a>            "Critical Region (alpha)" = "#1f78b4"</span>
<span id="cb8-222"><a></a>          )</span>
<span id="cb8-223"><a></a>        )</span>
<span id="cb8-224"><a></a>    }</span>
<span id="cb8-225"><a></a>    plt</span>
<span id="cb8-226"><a></a>    #ggplotly(plt)</span>
<span id="cb8-227"><a></a>  })  </span>
<span id="cb8-228"><a></a>}</span>
<span id="cb8-229"><a></a></span>
<span id="cb8-230"><a></a>shinyApp(ui, server)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!--Try adjusting the sample mean. How does the p-value change?-->
</section>

<section id="change-alpha-and-the-critical-value" class="title-slide slide level1 center">
<h1>Change <span class="math inline">\(\alpha\)</span> and the critical value</h1>
<ul>
<li>Suppose <span class="math inline">\(Z = 1.25\)</span> is fixed (e.g., we consider only one dataset)</li>
<li>How would the researcher’s decision about <span class="math inline">\(H_0\)</span> change with a different <span class="math inline">\(\alpha\)</span> (and critical value)? (note that <span class="math inline">\(\alpha\)</span> is rarely above .05)</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb9-1"><a></a>#| '!! shinylive warning !!': |</span>
<span id="cb9-2"><a></a>#|   shinylive does not work in self-contained HTML documents.</span>
<span id="cb9-3"><a></a>#|   Please set `embed-resources: false` in your metadata.</span>
<span id="cb9-4"><a></a>#| standalone: true</span>
<span id="cb9-5"><a></a>#| panel: fill</span>
<span id="cb9-6"><a></a>#| fig-align: center</span>
<span id="cb9-7"><a></a>#| viewerHeight: 550</span>
<span id="cb9-8"><a></a>library(tibble)</span>
<span id="cb9-9"><a></a>library(munsell)</span>
<span id="cb9-10"><a></a>library(shiny)</span>
<span id="cb9-11"><a></a>library(ggplot2)</span>
<span id="cb9-12"><a></a></span>
<span id="cb9-13"><a></a>ui &lt;- fluidPage(</span>
<span id="cb9-14"><a></a>  plotOutput(outputId = "alphaPlot1"),</span>
<span id="cb9-15"><a></a>  fluidRow(</span>
<span id="cb9-16"><a></a>    column(width = 4,</span>
<span id="cb9-17"><a></a>      sliderInput("alphaPlotVal", "α:", min = .01, max = .99, value = .05, step = .01)),</span>
<span id="cb9-18"><a></a>    column(width = 4,</span>
<span id="cb9-19"><a></a>      checkboxInput("shadealpha2", "Shade critical region (alpha)", value = TRUE),</span>
<span id="cb9-20"><a></a>      checkboxInput("shadep2", "Shade p-value area", value = FALSE))</span>
<span id="cb9-21"><a></a>  )</span>
<span id="cb9-22"><a></a>)</span>
<span id="cb9-23"><a></a></span>
<span id="cb9-24"><a></a>server &lt;- function(input, output){</span>
<span id="cb9-25"><a></a>  #library(plotly)</span>
<span id="cb9-26"><a></a>  theme_minimalism &lt;- function(base_size = 20) {</span>
<span id="cb9-27"><a></a>    theme_minimal(base_size = base_size) + # ggplot's minimal theme hides many unnecessary features of plot</span>
<span id="cb9-28"><a></a>      theme(</span>
<span id="cb9-29"><a></a>        # make modifications to the theme</span>
<span id="cb9-30"><a></a>        panel.grid.major.y = element_blank(), # hide major grid for y axis</span>
<span id="cb9-31"><a></a>        panel.grid.minor.y = element_blank(), # hide minor grid for y axis</span>
<span id="cb9-32"><a></a>        panel.grid.major.x = element_blank(), # hide major grid for x axis</span>
<span id="cb9-33"><a></a>        panel.grid.minor.x = element_blank(), # hide minor grid for x axis</span>
<span id="cb9-34"><a></a>        #text=element_text(size=14),           # font aesthetics</span>
<span id="cb9-35"><a></a>        #axis.text=element_text(size=12),</span>
<span id="cb9-36"><a></a>        #axis.title=element_text(size=14,face="bold"))</span>
<span id="cb9-37"><a></a>        axis.title = element_text(face = "bold")</span>
<span id="cb9-38"><a></a>      )</span>
<span id="cb9-39"><a></a>  }</span>
<span id="cb9-40"><a></a>  </span>
<span id="cb9-41"><a></a>  output$alphaPlot1 &lt;- renderPlot({</span>
<span id="cb9-42"><a></a>    twotailed &lt;- TRUE</span>
<span id="cb9-43"><a></a>    testval &lt;- 1.25</span>
<span id="cb9-44"><a></a>    lower &lt;- -3</span>
<span id="cb9-45"><a></a>    upper &lt;- 3</span>
<span id="cb9-46"><a></a>    mu &lt;- 0</span>
<span id="cb9-47"><a></a>    stdev &lt;- 1</span>
<span id="cb9-48"><a></a>  </span>
<span id="cb9-49"><a></a>    if (twotailed) {</span>
<span id="cb9-50"><a></a>      crit &lt;- qnorm(input$alphaPlotVal / 2, mean = 0, sd = 1, lower.tail = F)</span>
<span id="cb9-51"><a></a>    } else {</span>
<span id="cb9-52"><a></a>      crit &lt;- qnorm(input$alphaPlotVal, mean = 0, sd = 1, lower.tail = F)</span>
<span id="cb9-53"><a></a>    }</span>
<span id="cb9-54"><a></a>  </span>
<span id="cb9-55"><a></a>    plt &lt;- ggplot(data = data.frame(x = c(lower, upper)), aes(x)) +</span>
<span id="cb9-56"><a></a>      stat_function(</span>
<span id="cb9-57"><a></a>        fun = dnorm, #The Null Distribution</span>
<span id="cb9-58"><a></a>        args = list(mean = 0, sd = 1),</span>
<span id="cb9-59"><a></a>        geom = "area",</span>
<span id="cb9-60"><a></a>        linetype = "solid",</span>
<span id="cb9-61"><a></a>        fill = NA,</span>
<span id="cb9-62"><a></a>        size = 1.25,</span>
<span id="cb9-63"><a></a>        color = "#b2df8a",</span>
<span id="cb9-64"><a></a>        xlim = c(lower, upper)</span>
<span id="cb9-65"><a></a>      ) +</span>
<span id="cb9-66"><a></a>      geom_vline(xintercept = testval, alpha = .5) +</span>
<span id="cb9-67"><a></a>      annotate(</span>
<span id="cb9-68"><a></a>        "text",</span>
<span id="cb9-69"><a></a>        x = testval - .5,</span>
<span id="cb9-70"><a></a>        y = .26,</span>
<span id="cb9-71"><a></a>        label = paste0("Standardized sample mean \n Z = 1.25")</span>
<span id="cb9-72"><a></a>      )</span>
<span id="cb9-73"><a></a>  </span>
<span id="cb9-74"><a></a>    if (input$shadealpha2) {</span>
<span id="cb9-75"><a></a>      plt &lt;- plt +</span>
<span id="cb9-76"><a></a>        stat_function(</span>
<span id="cb9-77"><a></a>          fun = dnorm, # The critical region</span>
<span id="cb9-78"><a></a>          args = list(mean = mu, sd = stdev),</span>
<span id="cb9-79"><a></a>          geom = "area",</span>
<span id="cb9-80"><a></a>          fill = "#1f78b4",</span>
<span id="cb9-81"><a></a>          aes(color = "Critical Region (alpha)"),</span>
<span id="cb9-82"><a></a>          #color="#1f78b4",</span>
<span id="cb9-83"><a></a>          alpha = .25,</span>
<span id="cb9-84"><a></a>          xlim = {</span>
<span id="cb9-85"><a></a>            c(crit, upper)</span>
<span id="cb9-86"><a></a>          }</span>
<span id="cb9-87"><a></a>        )</span>
<span id="cb9-88"><a></a>      if (twotailed) {</span>
<span id="cb9-89"><a></a>        plt &lt;- plt +</span>
<span id="cb9-90"><a></a>          stat_function(</span>
<span id="cb9-91"><a></a>            fun = dnorm, # The critical region</span>
<span id="cb9-92"><a></a>            args = list(mean = mu, sd = stdev),</span>
<span id="cb9-93"><a></a>            geom = "area",</span>
<span id="cb9-94"><a></a>            fill = "#1f78b4",</span>
<span id="cb9-95"><a></a>            aes(color = "Critical Region (alpha)"),</span>
<span id="cb9-96"><a></a>            #color="#1f78b4",</span>
<span id="cb9-97"><a></a>            alpha = .25,</span>
<span id="cb9-98"><a></a>            xlim = {</span>
<span id="cb9-99"><a></a>              c(lower, -crit)</span>
<span id="cb9-100"><a></a>            }</span>
<span id="cb9-101"><a></a>          )</span>
<span id="cb9-102"><a></a>      }</span>
<span id="cb9-103"><a></a>    }</span>
<span id="cb9-104"><a></a>  </span>
<span id="cb9-105"><a></a>    if (input$shadep2) {</span>
<span id="cb9-106"><a></a>      plt &lt;- plt +</span>
<span id="cb9-107"><a></a>        stat_function(</span>
<span id="cb9-108"><a></a>          fun = dnorm, # The p-value</span>
<span id="cb9-109"><a></a>          args = list(mean = 0, sd = 1),</span>
<span id="cb9-110"><a></a>          geom = "area",</span>
<span id="cb9-111"><a></a>          linetype = "solid",</span>
<span id="cb9-112"><a></a>          fill = "#E69F00",</span>
<span id="cb9-113"><a></a>          aes(color = "p-value"),</span>
<span id="cb9-114"><a></a>          alpha = .35,</span>
<span id="cb9-115"><a></a>          xlim = c(testval, upper)</span>
<span id="cb9-116"><a></a>        )</span>
<span id="cb9-117"><a></a>      if (twotailed) {</span>
<span id="cb9-118"><a></a>        plt &lt;- plt +</span>
<span id="cb9-119"><a></a>          stat_function(</span>
<span id="cb9-120"><a></a>            fun = dnorm, # The p-value</span>
<span id="cb9-121"><a></a>            args = list(mean = 0, sd = 1),</span>
<span id="cb9-122"><a></a>            geom = "area",</span>
<span id="cb9-123"><a></a>            linetype = "solid",</span>
<span id="cb9-124"><a></a>            fill = "#E69F00",</span>
<span id="cb9-125"><a></a>            aes(color = "p-value"),</span>
<span id="cb9-126"><a></a>            alpha = .35,</span>
<span id="cb9-127"><a></a>            xlim = c(lower, -testval)</span>
<span id="cb9-128"><a></a>          )</span>
<span id="cb9-129"><a></a>      }</span>
<span id="cb9-130"><a></a>    }</span>
<span id="cb9-131"><a></a>  </span>
<span id="cb9-132"><a></a>    if (twotailed) {</span>
<span id="cb9-133"><a></a>      obtpval &lt;- pnorm(abs(testval), mean = mu, sd = stdev, lower.tail = F) * 2</span>
<span id="cb9-134"><a></a>      sig &lt;- ifelse(</span>
<span id="cb9-135"><a></a>        obtpval &lt; input$alphaPlotVal,</span>
<span id="cb9-136"><a></a>        "Significant",</span>
<span id="cb9-137"><a></a>        "Not Significant (n.s.)"</span>
<span id="cb9-138"><a></a>      )</span>
<span id="cb9-139"><a></a>      plt &lt;- plt +</span>
<span id="cb9-140"><a></a>        annotate(</span>
<span id="cb9-141"><a></a>          "text",</span>
<span id="cb9-142"><a></a>          x = 2.3,</span>
<span id="cb9-143"><a></a>          y = .37,</span>
<span id="cb9-144"><a></a>          label = paste0(sig, ",\n p = ", round(obtpval, 3)),</span>
<span id="cb9-145"><a></a>          vjust = 1,</span>
<span id="cb9-146"><a></a>          hjust = 1</span>
<span id="cb9-147"><a></a>        )</span>
<span id="cb9-148"><a></a>    } else {</span>
<span id="cb9-149"><a></a>      plt &lt;- plt +</span>
<span id="cb9-150"><a></a>        annotate(</span>
<span id="cb9-151"><a></a>          "text",</span>
<span id="cb9-152"><a></a>          x = 2.3,</span>
<span id="cb9-153"><a></a>          y = .37,</span>
<span id="cb9-154"><a></a>          label = paste0(</span>
<span id="cb9-155"><a></a>            if (testval &gt; crit) {</span>
<span id="cb9-156"><a></a>              "Significant"</span>
<span id="cb9-157"><a></a>            } else {</span>
<span id="cb9-158"><a></a>              "Not Significant (n.s.)"</span>
<span id="cb9-159"><a></a>            },</span>
<span id="cb9-160"><a></a>            ",\n p = ",</span>
<span id="cb9-161"><a></a>            round(pnorm(abs(testval), mean = mu, sd = stdev, lower.tail = F), 3)</span>
<span id="cb9-162"><a></a>          ),</span>
<span id="cb9-163"><a></a>          vjust = 1,</span>
<span id="cb9-164"><a></a>          hjust = 1</span>
<span id="cb9-165"><a></a>        )</span>
<span id="cb9-166"><a></a>    }</span>
<span id="cb9-167"><a></a>  </span>
<span id="cb9-168"><a></a>    plt &lt;- plt +</span>
<span id="cb9-169"><a></a>      #Clears the y-axis label</span>
<span id="cb9-170"><a></a>      ylab("") +</span>
<span id="cb9-171"><a></a>      xlab("Well-Being Score") +</span>
<span id="cb9-172"><a></a>      #Sets the x axis ticks to cover the whole plot</span>
<span id="cb9-173"><a></a>      scale_x_continuous(</span>
<span id="cb9-174"><a></a>        limits = c(lower, upper),</span>
<span id="cb9-175"><a></a>        breaks = seq(round(lower), round(upper), by = 1)</span>
<span id="cb9-176"><a></a>      ) +</span>
<span id="cb9-177"><a></a>      #Clears the y-axis ticks</span>
<span id="cb9-178"><a></a>      scale_y_continuous(breaks = NULL) +</span>
<span id="cb9-179"><a></a>      theme_minimalism()</span>
<span id="cb9-180"><a></a>  </span>
<span id="cb9-181"><a></a>    if (input$shadep2) {</span>
<span id="cb9-182"><a></a>      plt &lt;- plt +</span>
<span id="cb9-183"><a></a>        scale_colour_manual(</span>
<span id="cb9-184"><a></a>          "Legend",</span>
<span id="cb9-185"><a></a>          values = c(</span>
<span id="cb9-186"><a></a>            "Null Distribution" = "#b2df8a",</span>
<span id="cb9-187"><a></a>            "Critical Region (alpha)" = "#1f78b4",</span>
<span id="cb9-188"><a></a>            "p-value" = "#E69F00"</span>
<span id="cb9-189"><a></a>          )</span>
<span id="cb9-190"><a></a>        )</span>
<span id="cb9-191"><a></a>    } else {</span>
<span id="cb9-192"><a></a>      plt &lt;- plt +</span>
<span id="cb9-193"><a></a>        scale_colour_manual(</span>
<span id="cb9-194"><a></a>          "Legend",</span>
<span id="cb9-195"><a></a>          values = c(</span>
<span id="cb9-196"><a></a>            "Null Distribution" = "#b2df8a",</span>
<span id="cb9-197"><a></a>            "Critical Region (alpha)" = "#1f78b4"</span>
<span id="cb9-198"><a></a>          )</span>
<span id="cb9-199"><a></a>        )</span>
<span id="cb9-200"><a></a>    }</span>
<span id="cb9-201"><a></a>    plt</span>
<span id="cb9-202"><a></a>    #ggplotly(plt)</span>
<span id="cb9-203"><a></a>  })  </span>
<span id="cb9-204"><a></a>  </span>
<span id="cb9-205"><a></a>}</span>
<span id="cb9-206"><a></a></span>
<span id="cb9-207"><a></a>shinyApp(ui, server)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>

<section>
<section id="test-your-knowledge-1" class="title-slide slide level1 center">
<h1>Test your knowledge</h1>
<p>Scroll down to test your knowledge of null hypothesis significance testing and its components (<span class="math inline">\(p\)</span>-values, <span class="math inline">\(\alpha\)</span>, obtained test statistic, critical value)</p>
</section>
<section id="logic-of-hypothesis-testing" class="slide level2">
<h2>Logic of hypothesis testing</h2>
<div class="fragment">
<ul>
<li>When we say, “what distribution did the mean likely come from,” what are we really asking?</li>
</ul>
</div>
<div class="fragment">
<p>We want to know whether the observed mean from the sample (in our effort to estimate the population mean), is plausible under the null hypothesis. If it is not, we reject the null hypothesis in favor of the alternative hypothesis.</p>
</div>
<div class="fragment">
<ul>
<li>Is a single sample’s mean sufficient to tell us whether the alternative hypothesis is true?</li>
</ul>
</div>
<div class="fragment">
<p>No, hypothesis testing only evaluates whether the observed sample mean is likely or unlikely under the null hypothesis. It does not provide explicit information about the alternative hypothesis.</p>
</div>
</section>
<section id="components-of-hypothesis-testing" class="slide level2">
<h2>Components of hypothesis testing</h2>
<div class="fragment">
<ul>
<li>Are <span class="math inline">\(\alpha\)</span> and the critical value determined assuming <span class="math inline">\(H_0\)</span> is true or the alternative hypothesis is true?</li>
</ul>
</div>
<div class="fragment">
<p>The researcher chooses <span class="math inline">\(\alpha\)</span>. Its critical value is determined assuming <span class="math inline">\(H_0\)</span> is true. Each value of <span class="math inline">\(\alpha\)</span> has a one-to-one relationship with a corresponding critical value.</p>
</div>
<div class="fragment">
<ul>
<li>Is a <span class="math inline">\(p\)</span>-value the probability that <span class="math inline">\(H_0\)</span> is true?</li>
</ul>
</div>
<div class="fragment">
<p>No, but this is a common misconception.</p>
</div>
<div class="fragment">
<ul>
<li>What does a <span class="math inline">\(p\)</span>-value represent?</li>
</ul>
</div>
<div class="fragment">
<p>A <span class="math inline">\(p\)</span>-value is the probability of observing a test statistic as extreme or more extreme than that for our sample, if <span class="math inline">\(H_0\)</span> is true. In other words, it allows us to judge whether the observed data is incompatible with <span class="math inline">\(H_0\)</span>.</p>
</div>
</section>
<section id="components-of-hypothesis-testing-1" class="slide level2">
<h2>Components of hypothesis testing</h2>
<div class="fragment">
<ul>
<li>If an observed mean (or its corresponding observed test statistic) exceeds the critical value, what conclusion can we draw?</li>
</ul>
</div>
<div class="fragment">
<p>We conclude that the sample mean is unlikely to have come from the null distribution, so we reject the null hypothesis.</p>
</div>
<div class="fragment">
<ul>
<li>If an observed mean (or its corresponding observed test statistic) exceeds the critical value, will its corresponding <span class="math inline">\(p\)</span>-value be less than or greater than <span class="math inline">\(\alpha\)</span>?</li>
</ul>
</div>
<div class="fragment">
<p>If an observed test statistic is greater than the critical value, its corresponding <span class="math inline">\(p\)</span>-value will be less than <span class="math inline">\(\alpha\)</span>. Conversely, if an observed test statistic is less than the critical value, its corresponding <span class="math inline">\(p\)</span>-value will be greater than <span class="math inline">\(\alpha\)</span>. In general, use of either the test statistic or <span class="math inline">\(p\)</span>-value will yield the same conclusion.</p>
</div>
</section>
<section id="components-of-hypothesis-testing-2" class="slide level2">
<h2>Components of hypothesis testing</h2>
<div class="fragment">
<ul>
<li>What determines the size of the critical region?</li>
</ul>
</div>
<div class="fragment">
<p>Choice of <span class="math inline">\(\alpha\)</span>. <span class="math inline">\(\alpha\)</span> directly corresponds to the proportion of the null distribution that is in the critical region.</p>
</div>
<div class="fragment">
<ul>
<li>What determines the critical value (or cut-off for the critical region)?</li>
</ul>
</div>
<div class="fragment">
<p>The critical value, or cut-off/threshold, is primarily determined by <span class="math inline">\(\alpha\)</span>, but also requires knowledge of the null distribution.</p>
</div>
</section>
<section id="test-your-knowledge-2" class="slide level2">
<h2>Test your knowledge</h2>
<div class="fragment">
<ul>
<li>Suppose we set <span class="math inline">\(\alpha = .05\)</span>. Later we collect data, calculate a test statistic, and the <span class="math inline">\(p\)</span>-value = .08. Do we reject <span class="math inline">\(H_0\)</span>? What conclusion do we make?</li>
</ul>
</div>
<div class="fragment">
<p>In this case <span class="math inline">\(p &gt; \alpha\)</span>, so we do not reject <span class="math inline">\(H_0\)</span>. <!--Any difference between $\bar{x}$ and the hypothesized value under $H_0$ may be just due to chance.--></p>
</div>
<div class="fragment">
<ul>
<li>Suppose we set <span class="math inline">\(\alpha = .01\)</span>. Later we collect data, calculate a test statistic, and the <span class="math inline">\(p\)</span>-value = .03. Do we reject <span class="math inline">\(H_0\)</span>? What conclusion do we make?</li>
</ul>
</div>
<div class="fragment">
<p>Again, <span class="math inline">\(p &gt; \alpha\)</span>, so we do not reject <span class="math inline">\(H_0\)</span>. <!--Any difference between $\bar{x}$ and the hypothesized value under $H_0$ may be just due to chance.--></p>
</div>
<div class="fragment">
<ul>
<li>Under which situation are we more likely to reject <span class="math inline">\(H_0\)</span>: When <span class="math inline">\(\alpha=.05\)</span> or when <span class="math inline">\(\alpha = .10\)</span>?</li>
</ul>
</div>
<div class="fragment">
<p>When <span class="math inline">\(\alpha = .1\)</span>, there are more possible values of the test statistic that could result in rejecting <span class="math inline">\(H_0\)</span>. Though note that <span class="math inline">\(\alpha=.05\)</span> or <span class="math inline">\(\alpha=.01\)</span> are more typical choices in practice than <span class="math inline">\(\alpha=.1\)</span>.</p>
</div>
</section></section>
<section id="looking-ahead-other-test-statistics" class="title-slide slide level1 center">
<h1>Looking ahead: Other test statistics</h1>
<p>The same concepts in this module also apply to other kinds of hypothesis tests:</p>
<ul>
<li>single sample <span class="math inline">\(t\)</span>-tests, independent samples <span class="math inline">\(t\)</span>-tests, repeated measures <span class="math inline">\(t\)</span>-tests, Analysis of Variance (ANOVA), chi-square tests of independence, etc.</li>
</ul>
<ol type="1">
<li>The null hypothesis and desired test statistic imply a sampling distribution under <span class="math inline">\(H_0\)</span></li>
<li>A choice of <span class="math inline">\(\alpha\)</span> determines a cut-off value (i.e., critical value) under the sampling distribution for <span class="math inline">\(H_0\)</span></li>
<li>The obtained test statistic from the sample can be compared to the critical value <em>or</em></li>
<li>The <span class="math inline">\(p\)</span>-value can be compared to <span class="math inline">\(\alpha\)</span></li>
</ol>
</section>

<section id="thank-you" class="title-slide slide level1 center">
<h1>Thank you!</h1>
<p>This concludes the module on <span class="math inline">\(p\)</span>-values</p>
<p>This module made available by the Small Grants for Teaching opportunity from the Association for Psychological Science (APS Fund for Teaching and Public Understanding of Psychological Science)</p>
<p>Authors: Jeremy Rappel, Mira Saad, Carl F. Falk, Jens Kreitewolf</p>
<p>Initial Evaluation: Domi Wong</p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'h.v',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'default',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 800,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>